(function(root){
  'use strict';
  const node=typeof module==='object'&&module.exports,G=node?require('./shared.js'):root.LudiaGames,{text,choice,board}=node?require('./curriculum.js'):root.LudiaCurriculum,g=G.get('checkers');
  const fixture=(pieces,turn=1,forced=null)=>{const s={board:Array(64).fill(0),turn,forced,quiet:0,history:[],last:null};for(const [at,p]of pieces)s.board[at]=p;s.history=[g.key(s)];return s;};
  const chain=fixture([[42,1],[35,3],[21,3],[1,3]]),second=g.move(chain,{from:42,to:28});
  Object.assign(g,{title:text('Damas','Checkers'),description:text('Salta, captura y llega hasta la corona.','Jump, capture and reach the crown.'),tag:text('Pequeños pasos, grandes jugadas','Small steps, big moves'),lessons:[
    choice('board',text('Un tablero de dos colores','A board of two colours'),text('Jugamos damas inglesas en 8 × 8. Cada persona empieza con doce fichas en casillas oscuras.','We play English checkers on an 8 × 8 board. Each person starts with twelve pieces on dark squares.'),text('¿Por qué casillas se mueven las fichas?','Which squares do the pieces move on?'),[text('Por las oscuras','The dark squares'),text('Por todas','All squares')],0,text('Las fichas permanecen en las casillas oscuras.','Pieces stay on the dark squares.')),
    board('move',text('Un paso en diagonal','One diagonal step'),text('Una ficha normal avanza una casilla en diagonal. El destino debe estar vacío.','A regular piece moves one square diagonally forward. The destination must be empty.'),text('Mueve la ficha de c3 a b4.','Move the piece from c3 to b4.'),fixture([[42,1],[17,3]]),{from:42,to:33},text('Elige c3. Después elige b4, hacia arriba y a la izquierda.','Choose c3. Then choose b4, up and to the left.')),
    choice('turns',text('Un turno para cada persona','One turn for each person'),text('Las fichas claras empiezan y suben por el tablero. Las oscuras bajan. Os turnáis.','Light pieces start and move up the board. Dark pieces move down. Take turns.'),text('Acabas de mover una ficha clara sin capturar. ¿Quién juega?','You moved a light piece without capturing. Who plays next?'),[text('Las claras otra vez','Light again'),text('Las oscuras','Dark')],1,text('Después de una jugada normal, cambia el turno.','After a regular move, the turn changes.')),
    board('capture',text('Salta para capturar','Jump to capture'),text('Salta sobre una ficha rival que esté delante en diagonal. Aterriza justo después, en un hueco.','Jump over a rival piece diagonally ahead. Land on the empty square just beyond it.'),text('Salta de c3 a e5 y captura la ficha de d4.','Jump from c3 to e5 and capture the piece on d4.'),fixture([[42,1],[35,3],[1,3]]),{from:42,to:28},text('Elige c3 y después e5. La ficha intermedia sale del tablero.','Choose c3, then e5. The middle piece leaves the board.')),
    board('required',text('Si puedes capturar, debes hacerlo','If you can capture, you must'),text('Una captura tiene prioridad sobre un paso normal. Si hay varias capturas, eliges una.','A capture takes priority over a regular step. If there are several captures, choose one.'),text('Haz la captura disponible con la ficha de c3.','Make the available capture with the piece on c3.'),fixture([[42,1],[46,1],[35,3],[1,3]]),{from:42,to:28},text('La ficha de c3 puede saltar a e5. La de g3 debe esperar.','The c3 piece can jump to e5. The g3 piece must wait.')),
    board('chain',text('Completa todos los saltos','Complete every jump'),text('Si la misma ficha puede volver a capturar, sigue saltando en ese turno.','If the same piece can capture again, keep jumping in that turn.'),text('Ya has capturado una ficha. Continúa de e5 a g7.','You have captured one piece. Continue from e5 to g7.'),second,{from:28,to:14},text('Usa la misma ficha. Salta sobre f6 y aterriza en g7.','Use the same piece. Jump over f6 and land on g7.')),
    board('crown',text('Llega a la última fila','Reach the far row'),text('Al llegar al fondo, tu ficha se corona. Este turno termina, incluso si llegas capturando.','At the far row, your piece becomes a king. This turn ends, even if you arrive by capturing.'),text('Lleva la ficha de c7 a b8 para coronarla.','Move the piece from c7 to b8 to crown it.'),fixture([[10,1],[55,3]]),{from:10,to:1},text('La fila 8 está al fondo. Elige c7 y después b8.','Row 8 is at the far end. Choose c7, then b8.')),
    board('king',text('La dama puede volver atrás','A king can move backwards'),text('La ficha coronada lleva una corona. Se mueve una casilla en diagonal, hacia delante o atrás.','A crowned piece has a crown. It moves one diagonal square, forwards or backwards.'),text('Mueve la dama de e5 a d4, hacia atrás.','Move the king from e5 to d4, backwards.'),fixture([[28,2],[1,3]]),{from:28,to:35},text('Elige la ficha con corona. Después toca d4. También puede capturar hacia atrás.','Choose the crowned piece. Then choose d4. It can also capture backwards.')),
    board('win',text('Deja al rival sin jugadas','Leave the rival with no moves'),text('Ganas si el rival se queda sin fichas o sin movimientos legales.','Win if the rival has no pieces or no legal moves.'),text('Captura la última ficha oscura.','Capture the last dark piece.'),fixture([[42,1],[35,3]]),{from:42,to:28},text('Salta de c3 a e5. Ya no quedarán fichas oscuras.','Jump from c3 to e5. No dark pieces will remain.')),
    choice('draw',text('También hay empate','There are draws too'),text('En Ludia hay empate si la misma posición se repite tres veces. También tras 40 turnos por persona sin capturas ni coronas.','In Ludia, repeating the same position three times is a draw. So are 40 turns each without a capture or a new king.'),text('Se repite la misma posición tres veces, con el mismo turno. ¿Qué ocurre?','The same position repeats three times, with the same turn. What happens?'),[text('Hay empate','It is a draw'),text('Gana siempre la ficha coronada','The crowned piece always wins')],0,text('Ludia reconoce el empate automáticamente.','Ludia recognises the draw automatically.'))
  ]});
}(typeof window==='undefined'?globalThis:window));
