/* Editorial source: every sentence has a Spanish and an English version. */
(function (root) {
  'use strict';
  const G = typeof module === 'object' && module.exports ? require('./shared.js') : root.LudiaGames;
  const text = (es, en) => [es, en];
  const choice = (id, title, body, prompt, options, answer, hint) => ({ id, title, body, prompt, options, answer, hint, kind: 'choice' });
  const board = (id, title, body, prompt, setup, solution, hint, accept) => ({ id, title, body, prompt, setup, solution, hint, accept: accept || (a => JSON.stringify(a) === JSON.stringify(solution)), kind: 'board' });
  const tic = G.get('tic-tac-toe');
  Object.assign(tic, {
    title: text('Tres en raya', 'Tic-tac-toe'), description: text('Tres fichas. Una línea. Tu próxima jugada.', 'Three marks. One line. Your next move.'),
    tag: text('Conecta y descubre', 'Connect and discover'),
    lessons: [
      choice('board', text('Un tablero de nueve casillas', 'A board with nine spaces'), text('Hay tres filas y tres columnas. Cada casilla puede tener una ficha.', 'There are three rows and three columns. Each space can hold one mark.'), text('¿Cuántas fichas caben en una casilla?', 'How many marks fit in one space?'), [text('Una ficha', 'One mark'), text('Dos fichas', 'Two marks'), text('Tres fichas', 'Three marks')], 0, text('Cada casilla guarda una sola ficha.', 'Each space holds just one mark.')),
      board('empty', text('Elige una casilla vacía', 'Choose an empty space'), text('Tú usas ✕. El otro jugador usa ○. Las fichas se quedan donde las pones.', 'You use ✕. The other player uses ○. Marks stay where you place them.'), text('Pon ✕ en una casilla vacía.', 'Place ✕ in an empty space.'), { board: [2,0,0,0,1,0,0,0,0], turn: 1 }, { at: 2 }, text('Busca una casilla sin ✕ ni ○.', 'Find a space without ✕ or ○.'), a => a.at !== 0 && a.at !== 4),
      choice('turns', text('Una jugada por turno', 'One move each turn'), text('Empieza ✕. Después juega ○. Os turnáis hasta acabar la partida.', '✕ starts. Then ○ plays. Take turns until the game ends.'), text('Acabas de poner ✕. ¿Quién juega ahora?', 'You just placed ✕. Who plays next?'), [text('Otra vez ✕', '✕ again'), text('Ahora ○', '○ now')], 1, text('Después de ✕, le toca a ○.', 'After ✕, it is ○’s turn.')),
      board('row', text('Tres en una fila', 'Three in a row'), text('Ganas al unir tres fichas tuyas. Pueden estar en una línea horizontal.', 'Connect three of your marks to win. They can form a horizontal line.'), text('Completa la fila de arriba con ✕.', 'Complete the top row with ✕.'), { board: [1,1,0,2,2,0,0,0,0], turn: 1 }, { at: 2 }, text('Pon ✕ a la derecha de las otras dos.', 'Place ✕ to the right of the other two.')),
      board('column', text('Tres en una columna', 'Three in a column'), text('También ganas con una línea vertical. Las tres fichas deben ser tuyas.', 'A vertical line also wins. All three marks must be yours.'), text('Completa la columna de la izquierda.', 'Complete the left column.'), { board: [1,2,0,1,2,0,0,0,0], turn: 1 }, { at: 6 }, text('La casilla de abajo a la izquierda está vacía.', 'The bottom left space is empty.')),
      board('diagonal', text('Tres en diagonal', 'Three diagonally'), text('Una diagonal une dos esquinas opuestas. Pasa por el centro.', 'A diagonal joins opposite corners. It passes through the centre.'), text('Completa la diagonal de ✕.', 'Complete the diagonal of ✕.'), { board: [1,2,0,2,1,0,0,0,0], turn: 1 }, { at: 8 }, text('Une el centro con la esquina de abajo a la derecha.', 'Join the centre to the bottom right corner.')),
      board('block', text('Mira la jugada del otro', 'Look at the other player’s move'), text('Si el otro tiene dos en línea, puedes tapar su hueco.', 'If the other player has two in a line, you can fill their gap.'), text('Evita que ○ complete la fila de arriba.', 'Stop ○ completing the top row.'), { board: [2,2,0,1,0,0,0,1,0], turn: 1 }, { at: 2 }, text('Pon tu ficha junto a los dos círculos.', 'Place your mark beside the two circles.')),
      choice('draw', text('También podéis empatar', 'You can also draw'), text('Si se llena el tablero sin una línea ganadora, hay empate.', 'If the board fills without a winning line, the game is a draw.'), text('No quedan huecos. Nadie tiene tres en línea. ¿Qué ocurre?', 'No spaces remain. Nobody has three in a line. What happens?'), [text('Gana siempre ✕', '✕ always wins'), text('La partida es un empate', 'The game is a draw'), text('Se quitan todas las ○', 'Remove every ○')], 1, text('Si nadie gana y no quedan huecos, empatáis.', 'If nobody wins and no spaces remain, you draw.'))
    ]
  });
  const four=G.get('connect-four');
  const f=(placements,turn=1)=>{const s=four.init();for(const [at,p] of placements)s.board[at]=p;s.turn=turn;return s;};
  Object.assign(four,{title:text('Cuatro en raya','Connect four'),description:text('Deja caer una ficha. Conecta cuatro.', 'Drop a counter. Connect four.'),tag:text('Una línea, muchas posibilidades','One line, many possibilities'),lessons:[
    choice('board',text('Siete columnas para elegir','Seven columns to choose from'),text('El tablero tiene siete columnas y seis filas. Cada turno añades una ficha.','The board has seven columns and six rows. Add one counter each turn.'),text('¿Cuántas fichas pones en un turno?','How many counters do you place each turn?'),[text('Una','One'),text('Cuatro','Four')],0,text('Solo una. Después juega la otra persona.','Just one. Then the other person plays.')),
    board('gravity',text('Las fichas caen','Counters fall'),text('Elige una columna. La ficha cae hasta el primer hueco libre desde abajo.','Choose a column. The counter falls to the first free space from the bottom.'),text('Deja caer una ficha en la columna 4.','Drop a counter in column 4.'),f([[38,2]]),{col:3},text('Pulsa la flecha 4. La ficha quedará encima del círculo.','Press arrow 4. The counter will rest above the circle.')),
    board('horizontal',text('Cuatro en horizontal','Four horizontally'),text('Une cuatro fichas tuyas en una misma fila para ganar.','Connect four of your counters in one row to win.'),text('Completa la línea de abajo.','Complete the bottom line.'),f([[35,1],[36,1],[37,1],[39,2],[40,2]]),{col:3},text('La columna 4 completa la fila.','Column 4 completes the row.')),
    board('vertical',text('Cuatro en vertical','Four vertically'),text('Cuatro fichas tuyas en la misma columna también ganan.','Four of your counters in the same column also win.'),text('Completa la columna de la izquierda.','Complete the left column.'),f([[35,1],[28,1],[21,1],[36,2],[29,2],[38,2]]),{col:0},text('Deja caer la ficha en la columna 1.','Drop the counter in column 1.')),
    board('diagonal',text('Cuatro en diagonal','Four diagonally'),text('Una línea inclinada también cuenta. Necesitas apoyo debajo de cada ficha.','A sloping line counts too. Each counter needs support below it.'),text('Completa la diagonal que sube hacia la derecha.','Complete the diagonal rising to the right.'),f([[35,1],[36,2],[29,1],[37,2],[30,2],[23,1],[38,2],[31,1],[24,2]]),{col:3},text('La columna 4 deja tu ficha a la altura necesaria.','Column 4 places your counter at the right height.')),
    board('defend',text('Cierra el camino','Close the gap'),text('Mira las fichas del otro jugador. Puedes ocupar el hueco que necesita.','Look at the other player’s counters. You can fill the gap they need.'),text('Evita que ○ haga cuatro en la columna 6.','Stop ○ making four in column 6.'),f([[40,2],[33,2],[26,2],[35,1],[37,1],[38,1]]),{col:5},text('Pon tu ficha encima de los tres círculos.','Place your counter above the three circles.')),
    choice('full',text('Una columna llena','A full column'),text('Si una columna tiene seis fichas, está llena. Elige otra columna.','A column with six counters is full. Choose another column.'),text('La columna está llena. ¿Qué haces?','The column is full. What do you do?'),[text('Quitar una ficha del otro','Remove another player’s counter'),text('Elegir una columna con espacio','Choose a column with space')],1,text('Las fichas colocadas no se quitan.','Placed counters stay on the board.')),
    choice('finish',text('Victoria o empate','A win or a draw'),text('La partida acaba al unir cuatro. Si se llena sin ganador, hay empate.','The game ends when four connect. If it fills without a winner, it is a draw.'),text('Ya has unido cuatro. ¿Sigue la partida?','You have connected four. Does play continue?'),[text('No. Has ganado.','No. You have won.'),text('Sí. Hay que llenar el tablero.','Yes. Fill the board first.')],0,text('Conectar cuatro termina la partida.','Connecting four ends the game.'))
  ]});
  const sea=G.get('battleship');
  if(sea){const p=sea.init({},31);const battle=sea.move(sea.move(p,{type:'auto'}),{type:'start'});const hit=G.copy(battle);hit.shots[0]=[{at:hit.ships[1][0][0],hit:true},{at:hit.ships[1][0][1],hit:true}];
    Object.assign(sea,{title:text('Guerra de barcos','Battleship'),description:text('Explora el mar. Encuentra la flota oculta.','Explore the sea. Find the hidden fleet.'),tag:text('Rumbo a una nueva partida','Set sail for a new game'),lessons:[
      choice('fleet',text('Tu flota y el mar','Your fleet and the sea'),text('En el mar pequeño tienes tres barcos. Ocupan 3, 2 y 2 casillas.','In the small sea you have three ships. They take 3, 2 and 2 spaces.'),text('¿Cuántas casillas ocupa el barco más largo del mar pequeño?','How many spaces does the longest ship in the small sea take?'),[text('Una','One'),text('Tres','Three'),text('Seis','Six')],1,text('El barco más largo ocupa tres casillas seguidas.','The longest ship takes three spaces in a row.')),
      board('place',text('Coloca tus barcos','Place your ships'),text('Cada barco va en línea recta. Puede ir horizontal o vertical.','Each ship forms a straight line. It can be horizontal or vertical.'),text('Coloca el primer barco en horizontal desde la esquina de arriba a la izquierda.','Place the first ship horizontally from the top left corner.'),p,{type:'place',at:0,vertical:false},text('Elige la primera casilla. El barco ocupará tres huecos.','Choose the first space. The ship will cover three spaces.')),
      choice('overlap',text('Cada barco tiene su sitio','Each ship has its own space'),text('Dos barcos no pueden compartir casilla. Pueden tocarse por los lados.','Two ships cannot share a space. They may touch along their sides.'),text('¿Puedes colocar un barco encima de otro?','Can you put one ship on top of another?'),[text('Sí','Yes'),text('No','No')],1,text('Busca casillas libres dentro del tablero.','Find free spaces inside the board.')),
      choice('hidden',text('La otra flota está oculta','The other fleet is hidden'),text('Ves tus barcos. Los barcos de Ludia están ocultos hasta el final.','You can see your ships. Ludia’s ships stay hidden until the end.'),text('¿En qué mar buscas los barcos de Ludia?','In which sea do you search for Ludia’s ships?'),[text('En tu mar','In your sea'),text('En el mar de Ludia','In Ludia’s sea')],1,text('Dispara al mar de Ludia.','Fire at Ludia’s sea.')),
      board('shot',text('Un disparo cada turno','One shot each turn'),text('Elige una casilla que no hayas probado. Después dispara Ludia, aunque hayas acertado.','Choose a space you have not tried. Then Ludia fires, even if you hit.'),text('Prueba una casilla del mar de Ludia.','Try a space in Ludia’s sea.'),battle,{type:'fire',at:0},text('Cualquier casilla sin marca sirve.','Any unmarked space works.'),a=>a.type==='fire'),
      choice('water',text('Agua o tocado','Miss or hit'),text('Un punto significa agua. Una cruz significa que has tocado un barco.','A dot means water. A cross means you hit a ship.'),text('Ves una cruz después del disparo. ¿Qué has encontrado?','You see a cross after firing. What have you found?'),[text('Agua','Water'),text('Una parte de un barco','Part of a ship')],1,text('La cruz marca una parte de un barco.','The cross marks part of a ship.')),
      board('sink',text('Hunde un barco completo','Sink a whole ship'),text('Un barco se hunde cuando aciertas todas sus casillas.','A ship sinks when you hit every space it occupies.'),text('Las dos cruces son del mismo barco. Prueba la casilla que sigue la línea.','The two crosses belong to one ship. Try the next space along the line.'),hit,{type:'fire',at:hit.ships[1][0][2]},text('Sigue la dirección de las dos cruces.','Follow the direction of the two crosses.')),
      choice('win',text('Encuentra toda la flota','Find the whole fleet'),text('Gana quien hunda todos los barcos del otro. No hace falta probar todo el mar.','Sink every enemy ship to win. You do not need to try every sea space.'),text('Has hundido todos los barcos de Ludia. ¿Qué ocurre?','You have sunk every Ludia ship. What happens?'),[text('Has ganado la partida','You win the game'),text('Debes seguir disparando','You must keep firing')],0,text('La partida acaba cuando una flota queda hundida.','The game ends when a whole fleet is sunk.'))
    ]});}
  if (typeof module === 'object' && module.exports) module.exports = { text, choice, board };
  else root.LudiaCurriculum = { text, choice, board };
}(typeof window === 'undefined' ? globalThis : window));
