(function(root){
  'use strict';
  const node=typeof module==='object'&&module.exports,G=node?require('./shared.js'):root.LudiaGames,{text,choice,board}=node?require('./curriculum.js'):root.LudiaCurriculum,g=G.get('domino');
  const id=(a,b)=>g.tiles.findIndex(t=>t[0]===a&&t[1]===b);
  const fixture=(hand,chain,stock=[])=>({hands:[hand.map(t=>id(...t)),[id(1,1),id(2,2)]],stock:stock.map(t=>id(...t)),chain:chain.map(t=>({id:id(Math.min(...t),Math.max(...t)),left:t[0],right:t[1]})),turn:1,turnNumber:1,passes:0});
  const open=fixture([[2,4],[3,5]],[]),join=fixture([[2,4],[3,5]],[[1,2]]),draw=fixture([[3,5],[4,6]],[[1,2]],[[0,2],[5,6]]);
  Object.assign(g,{title:text('Dominó','Dominoes'),description:text('Une los puntos y encuentra tu siguiente ficha.','Match the dots and find your next tile.'),tag:text('Cada extremo abre un camino','Every end opens a path'),lessons:[
    choice('tile',text('Dos mitades en cada ficha','Two halves in each tile'),text('Cada ficha tiene dos mitades. Cada mitad muestra de cero a seis puntos.','Each tile has two halves. Each half shows zero to six dots.'),text('Una mitad no tiene puntos. ¿Qué valor tiene?','A half has no dots. What is its value?'),[text('Cero','Zero'),text('Uno','One'),text('Seis','Six')],0,text('Una mitad vacía vale cero.','An empty half is worth zero.')),
    board('start',text('Empieza con una ficha','Start with one tile'),text('Cada persona recibe siete fichas. En Ludia, el jugador 1 empieza con cualquiera.','Each person gets seven tiles. In Ludia, player 1 starts with any tile.'),text('Pon la ficha 2 | 4 para empezar.','Play the 2 | 4 tile to start.'),open,{type:'play',id:id(2,4),end:'right'},text('Elige 2 | 4. Después pulsa Colocar a la derecha.','Choose 2 | 4. Then press Place on the right.')),
    board('join',text('Une valores iguales','Match equal values'),text('Las mitades que se tocan deben tener el mismo valor. Ludia gira la ficha por ti.','Touching halves must have the same value. Ludia turns the tile for you.'),text('Une 2 | 4 al extremo derecho, que tiene un 2.','Join 2 | 4 to the right end, which has a 2.'),join,{type:'play',id:id(2,4),end:'right'},text('El 2 de tu ficha toca el 2 de la mesa.','The 2 on your tile touches the 2 on the table.')),
    board('ends',text('Puedes jugar en los dos extremos','You can play at either end'),text('Puedes añadir una ficha a la izquierda o a la derecha. El centro queda cerrado.','You can add a tile on the left or right. The middle stays closed.'),text('Coloca 1 | 6 en el extremo izquierdo.','Place 1 | 6 on the left end.'),fixture([[1,6],[3,5]],[[1,2]]),{type:'play',id:id(1,6),end:'left'},text('La mesa empieza con un 1. Une el 1 de tu ficha a ese lado.','The table starts with a 1. Match your tile’s 1 at that end.')),
    board('double',text('Una ficha doble','A double tile'),text('Una ficha doble tiene el mismo valor en ambas mitades. Se une como las demás.','A double tile has the same value on both halves. It joins like other tiles.'),text('Une el doble 2 | 2 al extremo derecho.','Join the double 2 | 2 to the right end.'),{...fixture([[2,2],[3,5]],[[1,2]]),hands:[[id(2,2),id(3,5)],[id(1,1),id(4,4)]]},{type:'play',id:id(2,2),end:'right'},text('Las dos mitades valen 2. Cualquiera encaja junto al 2.','Both halves are 2. Either fits beside the 2.')),
    board('draw',text('Roba si no puedes jugar','Draw if you cannot play'),text('Si ninguna ficha encaja, roba del montón. Sigue robando hasta poder jugar o agotarlo.','If no tile fits, draw from the stock. Keep drawing until you can play or it runs out.'),text('Ninguna ficha encaja. Roba una ficha.','No tile fits. Draw one tile.'),draw,{type:'draw'},text('Pulsa Robar ficha. Sigues en tu turno.','Press Draw tile. It is still your turn.')),
    board('pass',text('Pasa si no quedan fichas','Pass if the stock is empty'),text('Si no puedes jugar y el montón está vacío, pasa el turno.','If you cannot play and the stock is empty, pass your turn.'),text('No tienes un 1 ni un 2. El montón está vacío. Pasa.','You have no 1 or 2. The stock is empty. Pass.'),fixture([[3,5],[4,6]],[[1,2]]),{type:'pass'},text('Pulsa Pasar turno.','Press Pass turn.')),
    choice('finish',text('Vacía tu mano','Empty your hand'),text('Ganas al quedarte sin fichas. Si ambos pasáis seguidos, gana quien conserve menos puntos.','Win by using every tile. If both pass in a row, the lowest remaining dot total wins.'),text('Ambas personas pasan. Tienes 4 puntos y la otra tiene 7. ¿Quién gana?','Both people pass. You have 4 dots and the other has 7. Who wins?'),[text('Tú, porque tienes menos puntos','You, because you have fewer dots'),text('La otra persona, porque tiene más','The other person, because they have more')],0,text('En una partida bloqueada, gana la mano con menos puntos. Si son iguales, empatáis.','In a blocked game, the hand with fewer dots wins. Equal totals mean a draw.'))
  ]});
}(typeof window==='undefined'?globalThis:window));
