(function(root){
  'use strict';
  const node=typeof module==='object'&&module.exports,G=node?require('./shared.js'):root.LudiaGames,{text,choice,board}=node?require('./curriculum.js'):root.LudiaCurriculum;
  const sudoku=G.get('sudoku'),solution=[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1];
  const puzzle=(blanks)=>{const b=solution.map((v,i)=>blanks.includes(i)?0:v);return {size:4,board:b.slice(),givens:b.slice(),solution:solution.slice(),notes:Array.from({length:16},()=>[])};};const wrong=puzzle([0,5]);wrong.board[0]=2;
  Object.assign(sudoku,{title:text('Sudoku visual','Visual sudoku'),description:text('Formas que encajan. Un pequeño descubrimiento en cada hueco.','Shapes that fit. A small discovery in every space.'),tag:text('Encuentra la shape que falta','Find the missing shape'),lessons:[
    choice('symbols',text('Juega con shapes','Play with shapes'),text('En el tablero pequeño hay cuatro shapes: ● ▲ ■ ★. Cada shape tiene un número.','The small board has four shapes: ● ▲ ■ ★. Each shape has a number.'),text('¿Necesitas hacer sumas para jugar?','Do you need to add numbers to play?'),[text('Sí, hay que sumar','Yes, you need to add'),text('No, hay que colocar shapes','No, you place shapes')],1,text('Los números solo ayudan a reconocer las shapes.','The numbers only help you recognise the shapes.')),
    board('row',text('Una de cada shape en cada fila','One of each shape in each row'),text('Cada fila tiene todas las shapes. No puede repetir ninguna.','Each row has every shape. No shape can repeat.'),text('Completa la fila de arriba. Elige el hueco y después el círculo ●.','Complete the top row. Choose the empty space, then the circle ●.'),puzzle([0,5,10,15]),{type:'set',at:0,value:1},text('En la fila de arriba falta ●, la shape 1.','The top row is missing ●, shape 1.')),
    board('column',text('Mira también la column','Check the column too'),text('Cada column tiene todas las shapes sin repetir. Mira de arriba abajo.','Each column has every shape without repeats. Look from top to bottom.'),text('Completa el hueco de abajo en la primera column.','Fill the bottom space in the first column.'),puzzle([3,6,9,12]),{type:'set',at:12,value:4},text('La primera column tiene ●, ■ y ▲. Falta ★, la shape 4.','The first column has ●, ■ and ▲. It needs ★, shape 4.')),
    board('box',text('Los recuadros también cuentan','The boxes count too'),text('Las líneas gruesas separan recuadros. Cada recuadro tiene todas las shapes.','Thick lines separate boxes. Each box has every shape.'),text('Completa el recuadro de arriba a la izquierda.','Complete the top left box.'),puzzle([5,10,15]),{type:'set',at:5,value:4},text('En ese recuadro falta ★. Va en la fila 2, column 2.','That box needs ★. It goes in row 2, column 2.')),
    choice('given',text('Las pistas se quedan','The clues stay'),text('Las shapes con fondo oscuro son pistas iniciales. No puedes cambiarlas.','Shapes on a dark background are starting clues. You cannot change them.'),text('¿Qué shapes puedes erase?','Which shapes can you erase?'),[text('Las que has puesto tú','The ones you placed'),text('Todas, también las pistas iniciales','All of them, including starting clues')],0,text('Puedes cambiar tus propias answers. Las pistas quedan fijas.','You can change your answers. Starting clues stay fixed.')),
    board('correct',text('Cambia una shape repetida','Change a repeated shape'),text('Puedes check el tablero. Las repeticiones aparecen con un signo de exclamación.','You can check the board. Repeated shapes have an exclamation mark.'),text('Hay dos triángulos en la primera fila. Cambia el first por ●.','There are two triangles in the first row. Change the first one to ●.'),wrong,{type:'set',at:0,value:1},text('Elige la fila 1, column 1. Después elige ●.','Choose row 1, column 1. Then choose ●.')),
    board('notes',text('Puedes apuntar una idea','You can note an idea'),text('Activa Notas para apuntar shapes pequeñas. Una nota no completa la casilla.','Turn on Notes to write small shapes. A note does not fill the space.'),text('Activa Notas. Apunta ● en el primer hueco.','Turn on Notes. Note ● in the first empty space.'),puzzle([0,5,10,15]),{type:'note',at:0,value:1},text('Pulsa Notas. Elige la primera casilla y después ●.','Press Notes. Choose the first space, then ●.')),
    choice('finish',text('Completa el tablero','Complete the board'),text('Terminas cuando todos los huecos están llenos. Ninguna fila, column o recuadro repite shapes.','Finish when every space is filled. No row, column or box repeats a shape.'),text('Una fila tiene dos círculos. ¿Está terminado?','A row has two circles. Is the puzzle complete?'),[text('Sí, si no hay huecos','Yes, if no spaces are empty'),text('No, hay que corregir la repetición','No, the repetition needs fixing')],1,text('Todas las filas, columnas y recuadros deben fulfill la regla.','Every row, column and box must follow the rule.'))
  ]});
}(typeof window==='undefined'?globalThis:window));
