(function(root){
  'use strict';
  const node=typeof module==='object'&&module.exports,G=node?require('./shared.js'):root.LudiaGames,{text,choice,board}=node?require('./curriculum.js'):root.LudiaCurriculum,g=G.get('tetris');
  const empty=g.init({},3);empty.piece={type:'T',x:3,y:3,rotation:0};const line=G.copy(empty);line.piece={type:'I',x:3,y:3,rotation:0};line.board.splice(190,10,1,1,1,0,0,0,0,1,1,1);
  Object.assign(g,{title:text('Tetris','Tetris'),description:text('Gira, coloca y haz sitio a la siguiente pieza.','Rotate, place and make room for the next piece.'),tag:text('Dale forma a tu partida','Shape your game'),lessons:[
    choice('pieces',text('Piezas de cuatro bloques','Pieces of four blocks'),text('Cada pieza tiene cuatro bloques. Hay siete formas distintas.','Every piece has four blocks. There are seven different shapes.'),text('¿Cuántos bloques tiene cada pieza?','How many blocks does each piece have?'),[text('Dos','Two'),text('Cuatro','Four'),text('Siete','Seven')],1,text('Las siete formas tienen cuatro bloques cada una.','All seven shapes have four blocks each.')),
    board('move',text('Muévela a los lados','Move it sideways'),text('Puedes mover la pieza a izquierda o derecha antes de colocarla.','You can move the piece left or right before placing it.'),text('Mueve la pieza un paso a la izquierda.','Move the piece one step left.'),empty,{type:'left'},text('Pulsa la flecha que apunta a la izquierda.','Press the arrow pointing left.')),
    board('rotate',text('Gira la pieza','Rotate the piece'),text('Girar cambia la orientación. Una pieza nunca atraviesa paredes ni otros bloques.','Rotating changes the orientation. A piece never passes through walls or other blocks.'),text('Gira la pieza una vez hacia la derecha.','Rotate the piece once clockwise.'),empty,{type:'rotate'},text('Pulsa Girar. La pieza mantiene sus cuatro bloques.','Press Rotate. The piece keeps its four blocks.')),
    board('down',text('Baja paso a paso','Move down step by step'),text('En modo paso a paso, tú decides cuándo baja la pieza. No hay prisa.','In step mode, you decide when the piece moves down. Take your time.'),text('Baja la pieza un paso.','Move the piece down one step.'),empty,{type:'down'},text('Pulsa la flecha hacia abajo.','Press the down arrow.')),
    board('drop',text('La sombra te guía','The shadow guides you'),text('La sombra marca dónde quedará la pieza. Colocar la baja hasta ese lugar.','The shadow shows where the piece will land. Place moves it straight there.'),text('Coloca la pieza sobre su sombra.','Place the piece on its shadow.'),empty,{type:'drop'},text('Pulsa Colocar. Después aparece la siguiente pieza.','Press Place. The next piece then appears.')),
    board('line',text('Completa una fila','Complete a row'),text('Una fila llena desaparece. Los bloques de arriba bajan y dejan espacio.','A full row disappears. Blocks above move down and leave space.'),text('Coloca la barra para completar la fila de abajo.','Place the bar to complete the bottom row.'),line,{type:'drop'},text('La barra ya está sobre el hueco. Pulsa Colocar.','The bar is above the gap. Press Place.')),
    board('hold',text('Guarda una pieza para después','Save a piece for later'),text('Reservar guarda la pieza y trae otra. Puedes reservar una vez antes de colocar.','Hold saves the piece and brings another. You can hold once before placing.'),text('Reserva esta pieza.','Hold this piece.'),empty,{type:'hold'},text('Pulsa Reservar. La pieza aparecerá en la reserva.','Press Hold. The piece will appear in the hold box.')),
    choice('finish',text('Juega con espacio y a tu ritmo','Keep space and play at your pace'),text('Elige completar 5 o 10 filas, o jugar sin meta. Si no cabe la siguiente pieza, termina.','Choose to complete 5 or 10 rows, or play without a target. Play ends if the next piece cannot fit.'),text('Has elegido caída automática y quieres parar. ¿Qué haces?','You chose automatic falling and want to stop. What do you do?'),[text('Pulso Pausa','Press Pause'),text('Debo seguir hasta perder','Keep playing until losing')],0,text('Pausa detiene la caída. Puedes continuar después.','Pause stops the falling. You can continue later.'))
  ]});
}(typeof window==='undefined'?globalThis:window));
