(function(){
  'use strict';
  const G=window.LudiaGames,g=G.get('tetris');let running=false;
  Object.assign(window.LudiaCopy,{
    fall:['Caída de las piezas','Falling pieces'],manual:['Paso a paso · tú decides','Step by step · you decide'],slow:['Automática tranquila','Slow automatic'],steady:['Automática normal','Normal automatic'],target:['Meta de la partida','Game target'],fiveLines:['Completar 5 filas','Complete 5 rows'],tenLines:['Completar 10 filas','Complete 10 rows'],noTarget:['Sin meta de filas','No row target'],left:['Izquierda','Left'],right:['Derecha','Right'],down:['Bajar un paso','Move down'],rotatePiece:['Girar','Rotate'],drop:['Colocar','Place'],hold:['Reservar','Hold'],held:['Reserva','Hold box'],nextPiece:['Siguiente pieza','Next piece'],pause:['Pausa','Pause'],continueFall:['Continuar caída','Resume falling'],paused:['La caída está en pausa.','Falling is paused.'],falling:['Coloca las piezas y completa filas.','Place pieces and complete rows.'],stepMode:['Mueve la pieza. Tú decides cuándo baja.','Move the piece. You decide when it falls.'],lines:['Filas completas: {n}','Completed rows: {n}'],targetLines:['Meta: {n} filas','Target: {n} rows'],tetrisDone:['¡Meta completada!','Target complete!'],stackFull:['No cabe la siguiente pieza. Puedes deshacer o empezar otra partida.','The next piece cannot fit. You can undo or start another game.'],tetrisKeys:['Flechas: mover y girar. Espacio: colocar. Esc: pausa.','Arrows: move and rotate. Space: place. Esc: pause.'],block:['bloque','block'],fallingPiece:['pieza actual','current piece'],shadow:['sombra de la pieza','piece shadow'],tetrisHint:['Prueba esta acción: {action}.','Try this action: {action}.'],emptyHold:['Sin pieza reservada','No held piece'],holdUsed:['Ya has reservado. Coloca la pieza para reservar otra vez.','You already held a piece. Place it to hold again.']
  });
  window.LudiaOptions.tetris=({t,esc})=>`<label>${esc(t('fall'))}<select name="pace"><option value="manual">${esc(t('manual'))}</option><option value="slow">${esc(t('slow'))}</option><option value="steady">${esc(t('steady'))}</option></select></label><label>${esc(t('target'))}<select name="goal"><option value="5">${esc(t('fiveLines'))}</option><option value="10">${esc(t('tenLines'))}</option><option value="0">${esc(t('noTarget'))}</option></select></label>`;
  function mini(type,{esc,t}){return type?`<div class="tetromino-preview" role="img" aria-label="${esc(type)}" style="--piece-cols:${g.matrix({type,rotation:0}).length}">${g.matrix({type,rotation:0}).flat().map(v=>`<i class="${v?'tetromino-'+type:''}"></i>`).join('')}</div>`:`<span class="empty-hold">${esc(t('emptyHold'))}</span>`;}
  window.LudiaViews.tetris=(s,interactive,api)=>{
    const {t,esc,grid,button}=api,end=g.status(s),current=end.ended?[]:g.cells(s.piece).map(p=>p.y*10+p.x),shadow=end.ended?[]:g.cells(g.ghost(s)).map(p=>p.y*10+p.x);
    return `<div class="tetris-surface" tabindex="${interactive?0:-1}" aria-label="${esc(t('tetrisKeys'))}"><div class="tetris-stage">${grid(g,s,20,10,false,at=>({html:current.includes(at)?'<span>◆</span>':s.board[at]?'<span>▪</span>':'',label:current.includes(at)?t('fallingPiece')+' '+s.piece.type:s.board[at]?t('block'):shadow.includes(at)?t('shadow'):t('empty'),cls:current.includes(at)?'tetromino-'+s.piece.type+' falling-block':s.board[at]?'tetromino-'+g.types[s.board[at]-1]:shadow.includes(at)?'ghost-block':''}))}<div class="tetris-previews"><h2>${esc(t('nextPiece'))}</h2>${mini(s.queue[0],api)}<h2>${esc(t('held'))}</h2>${mini(s.hold,api)}</div></div>${interactive?`<div class="tetris-controls">${button('←','t-left','secondary',`aria-label="${esc(t('left'))}"`)}${button('↻ '+t('rotatePiece'),'t-rotate','secondary')}${button('→','t-right','secondary',`aria-label="${esc(t('right'))}"`)}${button('↓ '+t('down'),'t-down','secondary')}${button(t('drop'),'t-drop')}${button(t('hold'),'t-hold','secondary',s.held?'disabled':'')}</div><p class="keyboard-note">${esc(t('tetrisKeys'))}</p>`:''}</div>`;
  };
  window.LudiaStatus.tetris=(s,api)=>{const end=g.status(s);return end.ended?api.t(end.solved?'tetrisDone':'stackFull'):api.active?.options.pace==='manual'||!api.active?.options.pace?api.t('stepMode'):api.t(running?'falling':'paused');};
  window.LudiaPanels.tetris=(s,{t,esc,button,active})=>`<p class="stat-note">${esc(t('lines',{n:s.lines}))}</p>${s.goal?`<p>${esc(t('targetLines',{n:s.goal}))}</p>`:''}${active.options.pace&&active.options.pace!=='manual'&&!g.status(s).ended?button(t(running?'pause':'continueFall'),'pause','',`aria-pressed="${!running}"`):''}`;
  window.LudiaAction.tetris=(action,_control,_s,api,course)=>{if(action==='pause'){running=!running;api.renderLocal();return;}if(!action.startsWith('t-'))return;const a={type:action.slice(2)};course?api.tryExercise(a):api.commit(a);};
  window.LudiaHint.tetris=(_s,a,{t})=>t('tetrisHint',{action:t({rotate:'rotatePiece',left:'left',right:'right',down:'down',drop:'drop',hold:'hold'}[a.type])});
  window.LudiaTick=(s,api)=>{if(running&&api.active.options.pace!=='manual')api.setTimer(()=>api.commit({type:'down'}),api.active.options.pace==='steady'?700:1400);};
  window.LudiaUndo=(game)=>{if(game.id==='tetris')running=false;};
  window.addEventListener('hashchange',()=>{running=false;});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){running=false;window.Ludia.stop();}else if(location.hash==='#ludia/tetris/match')window.Ludia.api.renderLocal();});
  document.addEventListener('keydown',event=>{
    if(!location.hash.startsWith('#ludia/tetris/')||!event.target.closest('.tetris-surface'))return;
    const type={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',' ':'drop'}[event.key];
    if(type&&(event.key!==' '||event.target.classList.contains('tetris-surface'))){event.preventDefault();const course=location.hash.includes('/exercises/');course?window.Ludia.api.tryExercise({type}):window.Ludia.api.commit({type});}
    if(event.key==='Escape'){running=false;window.Ludia.stop();window.Ludia.api.renderLocal();}
  });
}());
