/* Enroca — en; Spanish is the editorial source of truth. */
window.App.i18n.register('en', {
  "lesson.board.title": "Meet the board",
  "lesson.board.intro": "The board is where you play.",
  "lesson.board.step.0": "The board has 64 squares. There are light and dark squares.",
  "lesson.board.step.1": "Put a light square in the right corner nearest you.",
  "lesson.board.step.2": "Letters and numbers give each square a name.",
  "lesson.board.q.0": "Which square goes in the right corner nearest you?",
  "lesson.board.q.0.hint": "Look at the bottom right corner. It is light.",
  "lesson.board.q.0.a.0": "A light square",
  "lesson.board.q.0.a.1": "A dark square",
  "lesson.board.q.0.a.2": "Either one",
  "lesson.board.q.1": "How many squares does the board have?",
  "lesson.board.q.1.hint": "There are 8 rows. Each row has 8 squares.",
  "lesson.board.q.1.a.0": "64 squares",
  "lesson.board.q.1.a.1": "8 squares",
  "lesson.board.q.1.a.2": "16 squares",
  "lesson.turns.title": "One move at a time",
  "lesson.turns.intro": "Each player takes a turn.",
  "lesson.turns.step.0": "One player has the white pieces. The other has the black pieces.",
  "lesson.turns.step.1": "White moves first. Then Black moves.",
  "lesson.turns.step.2": "Move one piece on your turn. Then wait for the other turn.",
  "lesson.turns.q.0": "Which pieces start the game?",
  "lesson.turns.q.0.hint": "White moves first. Then Black moves.",
  "lesson.turns.q.0.a.0": "White",
  "lesson.turns.q.0.a.1": "Black",
  "lesson.turns.q.0.a.2": "Both at once",
  "lesson.turns.q.1": "You just moved a white piece. What do you do now?",
  "lesson.turns.q.1.hint": "Each side has a turn. You do not move twice in a row.",
  "lesson.turns.q.1.a.0": "Wait for Black",
  "lesson.turns.q.1.a.1": "Move another white piece",
  "lesson.turns.q.1.a.2": "Move a black piece too",
  "lesson.rook.title": "The rook moves straight",
  "lesson.rook.intro": "Up, down or sideways.",
  "lesson.rook.step.0": "The rook moves in a straight line.",
  "lesson.rook.step.1": "It can move up, down, left or right.",
  "lesson.rook.step.2": "It can move several squares. It cannot jump over other pieces.",
  "lesson.rook.q.0": "How does the rook move?",
  "lesson.rook.q.0.hint": "The rook follows a row or a column.",
  "lesson.rook.q.0.a.0": "In a straight line",
  "lesson.rook.q.0.a.1": "Diagonally",
  "lesson.rook.q.0.a.2": "Jumping in an L shape",
  "lesson.rook.target": "Move the piece to d7.",
  "lesson.rook.target.hint": "Select the piece. Then select d7. Look at the path.",
  "lesson.bishop.title": "The bishop moves diagonally",
  "lesson.bishop.intro": "Follow a sloping path.",
  "lesson.bishop.step.0": "The bishop moves diagonally. This is a sloping path.",
  "lesson.bishop.step.1": "The bishop always stays on squares of the same color.",
  "lesson.bishop.step.2": "It can move several squares. It cannot jump over other pieces.",
  "lesson.bishop.q.0": "How does the bishop move?",
  "lesson.bishop.q.0.hint": "Look for the sloping path. Its squares have the same color.",
  "lesson.bishop.q.0.a.0": "Diagonally",
  "lesson.bishop.q.0.a.1": "Only forward",
  "lesson.bishop.q.0.a.2": "In a straight line",
  "lesson.bishop.target": "Move the piece to f6.",
  "lesson.bishop.target.hint": "Select the piece. Then select f6. Look at the path.",
  "lesson.queen.title": "The queen has two paths",
  "lesson.queen.intro": "Straight and diagonal.",
  "lesson.queen.step.0": "The queen can move in a straight line, like the rook.",
  "lesson.queen.step.1": "It can also move diagonally, like the bishop.",
  "lesson.queen.step.2": "It can move several squares. It cannot jump over other pieces.",
  "lesson.queen.q.0": "Which paths can the queen follow?",
  "lesson.queen.q.0.hint": "The queen combines the paths of the rook and bishop.",
  "lesson.queen.q.0.a.0": "Straight and diagonal",
  "lesson.queen.q.0.a.1": "Only diagonal",
  "lesson.queen.q.0.a.2": "Only one square forward",
  "lesson.queen.target": "Move the piece to g7.",
  "lesson.queen.target.hint": "Select the piece. Then select g7. Look at the path.",
  "lesson.king.title": "Look after your king",
  "lesson.king.intro": "One careful step.",
  "lesson.king.step.0": "The king moves one square in any direction.",
  "lesson.king.step.1": "The king cannot move to an attacked square.",
  "lesson.king.step.2": "The two kings can never stand on neighboring squares.",
  "lesson.king.q.0": "In an ordinary move, how far can the king go?",
  "lesson.king.q.0.hint": "The king takes one step. Then it waits for its next turn.",
  "lesson.king.q.0.a.0": "One square",
  "lesson.king.q.0.a.1": "A whole row",
  "lesson.king.q.0.a.2": "Three squares",
  "lesson.king.target": "Move the piece to e5.",
  "lesson.king.target.hint": "Select the piece. Then select e5. Look at the path.",
  "lesson.knight.title": "The knight jumps",
  "lesson.knight.intro": "Two squares, then one sideways.",
  "lesson.knight.step.0": "The knight moves in an L shape.",
  "lesson.knight.step.1": "Count two squares in a straight line. Then one to the side.",
  "lesson.knight.step.2": "The knight can jump over other pieces. Only the knight can jump.",
  "lesson.knight.q.0": "Which piece can jump over other pieces?",
  "lesson.knight.q.0.hint": "Remember the L-shaped jump.",
  "lesson.knight.q.0.a.0": "The knight",
  "lesson.knight.q.0.a.1": "The rook",
  "lesson.knight.q.0.a.2": "The bishop",
  "lesson.knight.target": "Move the piece to e6.",
  "lesson.knight.target.hint": "Select the piece. Then select e6. Look at the path.",
  "lesson.pawn.title": "The pawn moves forward",
  "lesson.pawn.intro": "Move straight. Capture diagonally.",
  "lesson.pawn.step.0": "The pawn moves one square forward. It cannot move backward.",
  "lesson.pawn.step.1": "From its starting square, it can move two squares if both are empty.",
  "lesson.pawn.step.2": "The pawn captures an opposing piece one square diagonally forward.",
  "lesson.pawn.q.0": "How does the pawn capture?",
  "lesson.pawn.q.0.hint": "It moves straight ahead. It captures diagonally.",
  "lesson.pawn.q.0.a.0": "One square diagonally forward",
  "lesson.pawn.q.0.a.1": "One square backward",
  "lesson.pawn.q.0.a.2": "Two squares sideways",
  "lesson.pawn.target": "Move the piece to d3.",
  "lesson.pawn.target.hint": "Select the piece. Then select d3. Look at the path.",
  "lesson.capture.title": "Capture a piece",
  "lesson.capture.intro": "Take the square of an opposing piece.",
  "lesson.capture.step.0": "To capture is to move onto an opposing piece’s square.",
  "lesson.capture.step.1": "The opposing piece leaves the board. Your piece takes its place.",
  "lesson.capture.step.2": "You cannot capture your own pieces. The king is never captured.",
  "lesson.capture.q.0": "Your rook meets a piece of your color. Can it capture it?",
  "lesson.capture.q.0.hint": "You can only capture pieces of the other color. The king is never captured.",
  "lesson.capture.q.0.a.0": "No. It is on my side",
  "lesson.capture.q.0.a.1": "Yes. It can capture it",
  "lesson.capture.q.0.a.2": "Yes. If it is a pawn",
  "lesson.capture.target": "Move the piece to d7.",
  "lesson.capture.target.hint": "Select the piece. Then select d7. Look at the path.",
  "lesson.check.title": "Check: protect the king",
  "lesson.check.intro": "Your king needs help.",
  "lesson.check.step.0": "You are in check when an opposing piece attacks your king.",
  "lesson.check.step.1": "You must escape check: move the king, block or capture the attacker.",
  "lesson.check.step.2": "If there is no escape, it is checkmate. The game ends.",
  "lesson.check.q.0": "Your king is in check. What must you do?",
  "lesson.check.q.0.hint": "Your next move must make your king safe.",
  "lesson.check.q.0.a.0": "Get the king out of check",
  "lesson.check.q.0.a.1": "Move any pawn",
  "lesson.check.q.0.a.2": "Wait one turn",
  "lesson.check.q.1": "There is check and no possible escape. What happens?",
  "lesson.check.q.1.hint": "The game ends before the king is captured.",
  "lesson.check.q.1.a.0": "It is checkmate. The game ends",
  "lesson.check.q.1.a.1": "The king jumps over another piece",
  "lesson.check.q.1.a.2": "The other side captures the king",
  "lesson.castle.title": "Castling",
  "lesson.castle.intro": "The king and rook move together.",
  "lesson.castle.step.0": "Castling is a special move with the king and a rook.",
  "lesson.castle.step.1": "The king moves two squares toward the rook. The rook lands beside the king.",
  "lesson.castle.step.2": "Neither piece may have moved before. The path must be empty.",
  "lesson.castle.step.3": "The king cannot be in check, cross an attack or finish under attack.",
  "lesson.castle.q.0": "Which pieces take part in castling?",
  "lesson.castle.q.0.hint": "Castling helps the king move together with a rook.",
  "lesson.castle.q.0.a.0": "The king and a rook",
  "lesson.castle.q.0.a.1": "The queen and a knight",
  "lesson.castle.q.0.a.2": "Two pawns",
  "lesson.castle.q.1": "Your king is in check. Can you castle now?",
  "lesson.castle.q.1.hint": "You cannot start castling when your king is in check.",
  "lesson.castle.q.1.a.0": "No. First you must escape check",
  "lesson.castle.q.1.a.1": "Yes. Always",
  "lesson.castle.q.1.a.2": "Yes. If the rook has not moved",
  "lesson.promotion.title": "A pawn transforms",
  "lesson.promotion.intro": "Reach the far end of the board.",
  "lesson.promotion.step.0": "When a pawn reaches the last row, it changes into another piece.",
  "lesson.promotion.step.1": "You can choose queen, rook, bishop or knight. This is called promotion.",
  "lesson.promotion.step.2": "You cannot choose a king or leave it as a pawn.",
  "lesson.promotion.q.0": "Your pawn reaches the last row. What can it become?",
  "lesson.promotion.q.0.hint": "You can choose queen, rook, bishop or knight.",
  "lesson.promotion.q.0.a.0": "A queen",
  "lesson.promotion.q.0.a.1": "Another king",
  "lesson.promotion.q.0.a.2": "It must stay a pawn",
  "lesson.promotion.q.1": "What is changing a pawn into another piece called?",
  "lesson.promotion.q.1.hint": "At the last row, the pawn transforms.",
  "lesson.promotion.q.1.a.0": "Promotion",
  "lesson.promotion.q.1.a.1": "Castling",
  "lesson.promotion.q.1.a.2": "Check",
  "lesson.enpassant.title": "En passant capture",
  "lesson.enpassant.intro": "A special capture between pawns.",
  "lesson.enpassant.step.0": "An opposing pawn moves two squares. It lands beside your pawn.",
  "lesson.enpassant.step.1": "You can capture it as if it had moved only one square.",
  "lesson.enpassant.step.2": "Your pawn moves diagonally to the square the other pawn skipped.",
  "lesson.enpassant.step.3": "You must do this on your very next move. Then the chance is gone.",
  "lesson.enpassant.q.0": "When can you make an en passant capture?",
  "lesson.enpassant.q.0.hint": "The chance lasts for just one move.",
  "lesson.enpassant.q.0.a.0": "Right after the two-square move",
  "lesson.enpassant.q.0.a.1": "On any later turn",
  "lesson.enpassant.q.0.a.2": "When a knight jumps",
  "lesson.enpassant.q.1": "Which pieces make an en passant capture?",
  "lesson.enpassant.q.1.hint": "It is a special move between two pawns.",
  "lesson.enpassant.q.1.a.0": "Pawns",
  "lesson.enpassant.q.1.a.1": "Rooks",
  "lesson.enpassant.q.1.a.2": "Kings",
  "lesson.draw.title": "A game can also be a draw",
  "lesson.draw.intro": "Sometimes neither side wins.",
  "lesson.draw.step.0": "A draw means neither side wins.",
  "lesson.draw.step.1": "If there are no legal moves and no check, it is stalemate: a draw.",
  "lesson.draw.step.2": "It is also a draw when only the two kings remain.",
  "lesson.draw.step.3": "When a position repeats three times, you can claim a draw.",
  "lesson.draw.q.0": "There is no check. You have no legal move. What happens?",
  "lesson.draw.q.0.hint": "In stalemate, the king is not attacked.",
  "lesson.draw.q.0.a.0": "It is stalemate. The game is drawn",
  "lesson.draw.q.0.a.1": "It is checkmate",
  "lesson.draw.q.0.a.2": "You can move an opposing piece",
  "lesson.draw.q.1": "Only the two kings remain. Who wins?",
  "lesson.draw.q.1.hint": "A king alone cannot give checkmate.",
  "lesson.draw.q.1.a.0": "Neither side. It is a draw",
  "lesson.draw.q.1.a.1": "White",
  "lesson.draw.q.1.a.2": "Black",
  "app.tagline": "Chess, step by step.",
  "app.title": "Enroca — Chess, step by step",
  "app.description": "Learn chess with short lessons, exercises and supported games.",
  "nav.home": "Home",
  "nav.learn": "Learn",
  "nav.practice": "Practice",
  "nav.play": "Play",
  "nav.settings": "Settings",
  "nav.skip": "Skip to content",
  "nav.suite": "More Apptonomia apps",
  "home.eyebrow": "ONE SMALL STEP. ONE NEW MOVE.",
  "home.title": "Chess starts with you.",
  "home.intro": "Meet the pieces. Try what you have learned. Enjoy a game.",
  "home.cta": "Let’s learn",
  "home.resume": "Pick up where you left off",
  "home.note": "No clock. With help. At your pace.",
  "home.path": "Your path into chess",
  "home.pathIntro": "Start with the first step or choose another.",
  "home.learn": "Meet the board and pieces through examples.",
  "home.practice": "Try what you remember. You can ask for a hint.",
  "home.play": "Make your next move with help beside you.",
  "home.learnCount": "14 short lessons",
  "home.practiceCount": "28 exercises to try",
  "home.playCount": "On your own or together",
  "home.progress": "You have read {n} of {total} lessons.",
  "home.start": "Every piece has its own path. Let’s discover it.",
  "common.back": "Back",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.done": "Read",
  "common.pending": "To discover",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.continue": "Continue",
  "common.listen": "Listen",
  "common.stop": "Stop listening",
  "common.voiceUnavailable": "No local voice is available. You can keep reading.",
  "common.offline": "You are offline. You can keep playing.",
  "common.storageUnavailable": "You can continue. This browser cannot save your progress.",
  "common.saved": "Your progress is saved on this device.",
  "learn.title": "Learn one thing at a time.",
  "learn.intro": "Look at the example. Read or listen. Repeat whenever you like.",
  "learn.step": "Step {n} of {total}",
  "learn.example": "See an example",
  "learn.reset": "See the starting position",
  "learn.diagram": "Example board",
  "learn.legend": "Dots show destinations. Pieces follow their own movement rule.",
  "learn.finish": "I have read this lesson",
  "learn.finished": "Lesson read. Now you can try what you learned.",
  "learn.practice": "Practice this lesson",
  "learn.other": "See the lessons",
  "learn.readAgain": "Read again",
  "learn.reading": "Read lesson",
  "practice.title": "Let’s try what you learned.",
  "practice.intro": "One exercise at a time. Hints are here to help.",
  "practice.all": "Practice from the beginning",
  "practice.review": "Choose a lesson to practice",
  "practice.summary": "You have solved {n} of {total} exercises.",
  "practice.number": "Exercise {n} of {total}",
  "practice.hint": "Give me a hint",
  "practice.lesson": "Back to the lesson",
  "practice.return": "Back to the exercise",
  "practice.again": "Let’s look again. You can try another answer.",
  "practice.right": "You found it!",
  "practice.supported": "Solved with help. You can try again whenever you like.",
  "practice.independent": "Solved without a hint",
  "practice.withHint": "Solved with help",
  "practice.choosePiece": "First select the piece you want to move.",
  "practice.chooseSquare": "Now select the destination square.",
  "practice.invalid": "That is not the destination we are looking for. Look at the question.",
  "practice.complete": "You have finished this practice.",
  "practice.completeText": "You can repeat, read another lesson or play a game.",
  "practice.repeat": "Repeat this practice",
  "practice.toGame": "Let’s play",
  "play.title": "Every move is a new step.",
  "play.intro": "Choose how to play. Help is available during the game.",
  "play.boardType": "How many pieces?",
  "play.mini": "First steps",
  "play.miniDesc": "Fewer pieces. You have a rook to help you.",
  "play.full": "All the pieces",
  "play.fullDesc": "The full board. The same help.",
  "play.partner": "Who will you play with?",
  "play.computer": "With Enroca",
  "play.computerDesc": "You play White. Enroca plays Black.",
  "play.local": "With another person",
  "play.localDesc": "Share this device and take turns.",
  "play.start": "Start the game",
  "play.resume": "Continue my game",
  "play.new": "New game",
  "play.newTitle": "Start another game?",
  "play.newText": "A new game will replace this game. Your lessons stay saved.",
  "play.whiteTurn": "White to move",
  "play.blackTurn": "Black to move",
  "play.thinking": "Enroca is choosing a move.",
  "play.select": "1. Select one of your pieces.",
  "play.destination": "2. Select a destination with a dot or a ring.",
  "play.selected": "{piece} on {square}. Choose its destination.",
  "play.noMoves": "That piece cannot move now. Try another one.",
  "play.invalid": "That move is not allowed. Try a marked destination.",
  "play.check": "Check. Your next move must protect the king.",
  "play.hint": "Help me choose",
  "play.undo": "Undo move",
  "play.hintText": "You can move {piece} from {from} to {to}.",
  "play.legend": "● You can move here · ◎ You can capture here",
  "play.board": "Chessboard. Use the arrow keys to move between squares.",
  "play.keyboard": "Keyboard: arrows to choose a square. Enter to select. Escape to release.",
  "play.empty": "{square}, empty",
  "play.square": "{square}, {side}: {piece}",
  "play.destinationLabel": "possible destination",
  "play.captureLabel": "possible capture",
  "play.selectedLabel": "selected",
  "play.white": "White",
  "play.black": "Black",
  "play.you": "You",
  "play.moved": "{side}: {piece}, from {from} to {to}.",
  "play.captured": "Captures {piece}.",
  "play.castled": "The king and rook have castled.",
  "play.promoted": "The pawn has become a {piece}.",
  "play.enpassant": "En passant: the pawn on the neighboring square is removed.",
  "play.lastMove": "Last move",
  "play.noLastMove": "White moves first.",
  "play.promotion": "Your pawn has arrived. Choose its new piece.",
  "play.mate": "Checkmate. {side} wins.",
  "play.stalemate": "Draw by stalemate. There is no check and no possible move.",
  "play.material": "Draw. These pieces cannot give checkmate.",
  "play.fivefold": "Draw. The same position has repeated five times.",
  "play.seventyfive": "Draw. Each side has made 75 moves without a pawn move or capture.",
  "play.fifty": "Draw claimed after 50 moves per side without a pawn move or capture.",
  "play.threefold": "Draw claimed after the same position appeared three times.",
  "play.claim": "Claim a draw",
  "play.claimAvailable": "You can claim a draw for repetition or many turns without progress.",
  "play.endNote": "You can look at the board or start another game.",
  "play.history": "See this game’s moves",
  "piece.p": "pawn",
  "piece.r": "rook",
  "piece.n": "knight",
  "piece.b": "bishop",
  "piece.q": "queen",
  "piece.k": "king",
  "settings.title": "Make it work for you.",
  "settings.intro": "Choose the help that feels right for you.",
  "settings.language": "Language",
  "settings.text": "Text size",
  "settings.regular": "Regular",
  "settings.large": "Large",
  "settings.contrast": "High contrast",
  "settings.pieceNames": "Show names below pieces",
  "settings.data": "What Enroca saves",
  "settings.dataText": "Your read lessons, solved exercises, settings and current game are saved here.",
  "settings.privacy": "Everything stays in this browser. You do not need an account.",
  "settings.delete": "Delete my data",
  "settings.confirmTitle": "Delete your Enroca data?",
  "settings.confirmText": "Your progress, settings and game on this device will be deleted.",
  "settings.confirm": "Yes, delete my data",
  "settings.deleted": "Your Enroca data has been deleted.",
  "footer.note": "An Apptonomia app. Learn at your pace.",
  "privacy.title": "Your data stays with you.",
  "privacy.intro": "Enroca does not ask for your name or email.",
  "privacy.storage": "It saves your progress and game only in this browser.",
  "privacy.tracking": "It uses no cookies, ads, accounts or tracking.",
  "privacy.voice": "Listen uses a voice on your device. If none is available, you can read.",
  "privacy.reset": "You can delete your data in Settings.",
  "privacy.link": "Privacy",
  "support.link": "Support guide",
  "play.list": "Move using a list",
  "play.from": "Choose a piece",
  "play.to": "Choose its destination",
  "play.move": "Move the piece",
  "play.choose": "Choose an option",
  "play.listHelp": "You can also choose squares using these larger controls."
});
