/* Enroca — es; Spanish is the editorial source of truth. */
window.App.i18n.register('es', {
  "lesson.board.title": "Conoce el tablero",
  "lesson.board.intro": "El tablero es el lugar donde juegas.",
  "lesson.board.step.0": "El tablero tiene 64 casillas. Hay casillas claras y oscuras.",
  "lesson.board.step.1": "Coloca una casilla clara en la esquina derecha, cerca de ti.",
  "lesson.board.step.2": "Las letras y los números dan un nombre a cada casilla.",
  "lesson.board.q.0": "¿Qué casilla va en la esquina derecha, cerca de ti?",
  "lesson.board.q.0.hint": "Mira la esquina de abajo a la derecha. Es clara.",
  "lesson.board.q.0.a.0": "Una casilla clara",
  "lesson.board.q.0.a.1": "Una casilla oscura",
  "lesson.board.q.0.a.2": "Da igual",
  "lesson.board.q.1": "¿Cuántas casillas tiene el tablero?",
  "lesson.board.q.1.hint": "Hay 8 filas. Cada fila tiene 8 casillas.",
  "lesson.board.q.1.a.0": "64 casillas",
  "lesson.board.q.1.a.1": "8 casillas",
  "lesson.board.q.1.a.2": "16 casillas",
  "lesson.turns.title": "Una jugada cada vez",
  "lesson.turns.intro": "Cada persona tiene su turno.",
  "lesson.turns.step.0": "Una persona lleva las piezas blancas. La otra lleva las negras.",
  "lesson.turns.step.1": "Las blancas empiezan. Después juegan las negras.",
  "lesson.turns.step.2": "Mueve una pieza en tu turno. Después espera el otro turno.",
  "lesson.turns.q.0": "¿Qué piezas empiezan la partida?",
  "lesson.turns.q.0.hint": "Primero juegan las blancas. Después juegan las negras.",
  "lesson.turns.q.0.a.0": "Las blancas",
  "lesson.turns.q.0.a.1": "Las negras",
  "lesson.turns.q.0.a.2": "Las dos a la vez",
  "lesson.turns.q.1": "Acabas de mover tus piezas blancas. ¿Qué haces ahora?",
  "lesson.turns.q.1.hint": "Cada lado tiene su turno. No mueves dos veces seguidas.",
  "lesson.turns.q.1.a.0": "Esperar a las negras",
  "lesson.turns.q.1.a.1": "Mover otra pieza blanca",
  "lesson.turns.q.1.a.2": "Mover una pieza negra también",
  "lesson.rook.title": "La torre va recta",
  "lesson.rook.intro": "Arriba, abajo o hacia los lados.",
  "lesson.rook.step.0": "La torre se mueve en línea recta.",
  "lesson.rook.step.1": "Puede ir arriba, abajo, a la izquierda o a la derecha.",
  "lesson.rook.step.2": "Puede avanzar varias casillas. No puede saltar otras piezas.",
  "lesson.rook.q.0": "¿Cómo se mueve la torre?",
  "lesson.rook.q.0.hint": "La torre va por una fila o por una columna.",
  "lesson.rook.q.0.a.0": "En línea recta",
  "lesson.rook.q.0.a.1": "En diagonal",
  "lesson.rook.q.0.a.2": "Saltando en forma de L",
  "lesson.rook.target": "Mueve la pieza a d7.",
  "lesson.rook.target.hint": "Toca la pieza. Después toca d7. Mira el camino.",
  "lesson.bishop.title": "El alfil va en diagonal",
  "lesson.bishop.intro": "Sigue un camino inclinado.",
  "lesson.bishop.step.0": "El alfil se mueve en diagonal. Es un camino inclinado.",
  "lesson.bishop.step.1": "El alfil siempre sigue casillas del mismo color.",
  "lesson.bishop.step.2": "Puede avanzar varias casillas. No puede saltar otras piezas.",
  "lesson.bishop.q.0": "¿Cómo se mueve el alfil?",
  "lesson.bishop.q.0.hint": "Busca el camino inclinado. Sus casillas tienen el mismo color.",
  "lesson.bishop.q.0.a.0": "En diagonal",
  "lesson.bishop.q.0.a.1": "Solo hacia delante",
  "lesson.bishop.q.0.a.2": "En línea recta",
  "lesson.bishop.target": "Mueve la pieza a f6.",
  "lesson.bishop.target.hint": "Toca la pieza. Después toca f6. Mira el camino.",
  "lesson.queen.title": "La dama tiene dos caminos",
  "lesson.queen.intro": "En línea recta y en diagonal.",
  "lesson.queen.step.0": "La dama puede moverse en línea recta, como la torre.",
  "lesson.queen.step.1": "También puede moverse en diagonal, como el alfil.",
  "lesson.queen.step.2": "Puede avanzar varias casillas. No puede saltar otras piezas.",
  "lesson.queen.q.0": "¿Qué caminos puede seguir la dama?",
  "lesson.queen.q.0.hint": "La dama combina los caminos de la torre y del alfil.",
  "lesson.queen.q.0.a.0": "Rectos y diagonales",
  "lesson.queen.q.0.a.1": "Solo diagonales",
  "lesson.queen.q.0.a.2": "Solo una casilla hacia delante",
  "lesson.queen.target": "Mueve la pieza a g7.",
  "lesson.queen.target.hint": "Toca la pieza. Después toca g7. Mira el camino.",
  "lesson.king.title": "Cuida a tu rey",
  "lesson.king.intro": "Un paso, con cuidado.",
  "lesson.king.step.0": "El rey se mueve una casilla en cualquier dirección.",
  "lesson.king.step.1": "El rey no puede ir a una casilla atacada.",
  "lesson.king.step.2": "Los dos reyes nunca pueden estar en casillas vecinas.",
  "lesson.king.q.0": "En un movimiento normal, ¿cuánto avanza el rey?",
  "lesson.king.q.0.hint": "El rey da un paso. Después espera su próximo turno.",
  "lesson.king.q.0.a.0": "Una casilla",
  "lesson.king.q.0.a.1": "Toda una fila",
  "lesson.king.q.0.a.2": "Tres casillas",
  "lesson.king.target": "Mueve la pieza a e5.",
  "lesson.king.target.hint": "Toca la pieza. Después toca e5. Mira el camino.",
  "lesson.knight.title": "El caballo salta",
  "lesson.knight.intro": "Dos casillas y una al lado.",
  "lesson.knight.step.0": "El caballo se mueve en forma de L.",
  "lesson.knight.step.1": "Cuenta dos casillas en línea recta. Después, una hacia un lado.",
  "lesson.knight.step.2": "El caballo puede saltar otras piezas. Es la única pieza que salta.",
  "lesson.knight.q.0": "¿Qué pieza puede saltar otras piezas?",
  "lesson.knight.q.0.hint": "Recuerda el salto en forma de L.",
  "lesson.knight.q.0.a.0": "El caballo",
  "lesson.knight.q.0.a.1": "La torre",
  "lesson.knight.q.0.a.2": "El alfil",
  "lesson.knight.target": "Mueve la pieza a e6.",
  "lesson.knight.target.hint": "Toca la pieza. Después toca e6. Mira el camino.",
  "lesson.pawn.title": "El peón va hacia delante",
  "lesson.pawn.intro": "Avanza recto. Captura en diagonal.",
  "lesson.pawn.step.0": "El peón avanza una casilla hacia delante. No retrocede.",
  "lesson.pawn.step.1": "Desde su casilla inicial, puede avanzar dos casillas si están libres.",
  "lesson.pawn.step.2": "El peón captura una pieza contraria en la casilla diagonal de delante.",
  "lesson.pawn.q.0": "¿Cómo captura el peón?",
  "lesson.pawn.q.0.hint": "Para avanzar va recto. Para capturar va en diagonal.",
  "lesson.pawn.q.0.a.0": "Una casilla en diagonal hacia delante",
  "lesson.pawn.q.0.a.1": "Una casilla hacia atrás",
  "lesson.pawn.q.0.a.2": "Dos casillas hacia un lado",
  "lesson.pawn.target": "Mueve la pieza a d3.",
  "lesson.pawn.target.hint": "Toca la pieza. Después toca d3. Mira el camino.",
  "lesson.capture.title": "Capturar una pieza",
  "lesson.capture.intro": "Ocupa la casilla de una pieza contraria.",
  "lesson.capture.step.0": "Capturar es llegar a la casilla de una pieza contraria.",
  "lesson.capture.step.1": "La pieza contraria sale del tablero. Tu pieza ocupa su lugar.",
  "lesson.capture.step.2": "No puedes capturar tus propias piezas. El rey nunca se captura.",
  "lesson.capture.q.0": "Tu torre encuentra una pieza de tu color. ¿Puede capturarla?",
  "lesson.capture.q.0.hint": "Solo puedes capturar piezas del otro color. El rey nunca se captura.",
  "lesson.capture.q.0.a.0": "No. Es una pieza de mi lado",
  "lesson.capture.q.0.a.1": "Sí. Puede capturarla",
  "lesson.capture.q.0.a.2": "Sí. Si es un peón",
  "lesson.capture.target": "Mueve la pieza a d7.",
  "lesson.capture.target.hint": "Toca la pieza. Después toca d7. Mira el camino.",
  "lesson.check.title": "Jaque: protege al rey",
  "lesson.check.intro": "Tu rey necesita ayuda.",
  "lesson.check.step.0": "Hay jaque cuando una pieza contraria ataca a tu rey.",
  "lesson.check.step.1": "Debes quitar el jaque: mover el rey, tapar el ataque o capturar.",
  "lesson.check.step.2": "Si no hay ninguna salida, es jaque mate. La partida termina.",
  "lesson.check.q.0": "Tu rey está en jaque. ¿Qué debes hacer?",
  "lesson.check.q.0.hint": "Tu próxima jugada debe dejar a tu rey a salvo.",
  "lesson.check.q.0.a.0": "Quitar el ataque al rey",
  "lesson.check.q.0.a.1": "Mover cualquier peón",
  "lesson.check.q.0.a.2": "Esperar un turno",
  "lesson.check.q.1": "Hay jaque y no existe ninguna salida. ¿Qué ocurre?",
  "lesson.check.q.1.hint": "La partida termina antes de capturar al rey.",
  "lesson.check.q.1.a.0": "Es jaque mate. La partida termina",
  "lesson.check.q.1.a.1": "El rey salta sobre otra pieza",
  "lesson.check.q.1.a.2": "El otro lado captura al rey",
  "lesson.castle.title": "El enroque",
  "lesson.castle.intro": "El rey y la torre se mueven juntos.",
  "lesson.castle.step.0": "El enroque es una jugada especial del rey y una torre.",
  "lesson.castle.step.1": "El rey avanza dos casillas hacia la torre. La torre queda junto al rey.",
  "lesson.castle.step.2": "Ninguna de esas piezas puede haberse movido. El camino debe estar libre.",
  "lesson.castle.step.3": "El rey no puede estar en jaque, pasar por un ataque ni acabar atacado.",
  "lesson.castle.q.0": "¿Qué piezas participan en el enroque?",
  "lesson.castle.q.0.hint": "Enrocar ayuda al rey a cambiar de lugar junto a una torre.",
  "lesson.castle.q.0.a.0": "El rey y una torre",
  "lesson.castle.q.0.a.1": "La dama y un caballo",
  "lesson.castle.q.0.a.2": "Dos peones",
  "lesson.castle.q.1": "Tu rey está en jaque. ¿Puedes enrocar ahora?",
  "lesson.castle.q.1.hint": "El enroque no puede empezar con el rey en jaque.",
  "lesson.castle.q.1.a.0": "No. Primero hay que quitar el jaque",
  "lesson.castle.q.1.a.1": "Sí. Siempre",
  "lesson.castle.q.1.a.2": "Sí. Si la torre no se ha movido",
  "lesson.promotion.title": "Un peón se transforma",
  "lesson.promotion.intro": "Llega al otro extremo del tablero.",
  "lesson.promotion.step.0": "Cuando un peón llega a la última fila, cambia de pieza.",
  "lesson.promotion.step.1": "Puedes elegir dama, torre, alfil o caballo. Esto se llama coronación.",
  "lesson.promotion.step.2": "No puedes elegir un rey ni dejarlo como peón.",
  "lesson.promotion.q.0": "Tu peón llega a la última fila. ¿En qué puede convertirse?",
  "lesson.promotion.q.0.hint": "Puedes elegir dama, torre, alfil o caballo.",
  "lesson.promotion.q.0.a.0": "En una dama",
  "lesson.promotion.q.0.a.1": "En otro rey",
  "lesson.promotion.q.0.a.2": "Debe seguir siendo peón",
  "lesson.promotion.q.1": "¿Cómo se llama el cambio del peón por otra pieza?",
  "lesson.promotion.q.1.hint": "Al llegar a la última fila, el peón se transforma.",
  "lesson.promotion.q.1.a.0": "Coronación",
  "lesson.promotion.q.1.a.1": "Enroque",
  "lesson.promotion.q.1.a.2": "Jaque",
  "lesson.enpassant.title": "La captura al paso",
  "lesson.enpassant.intro": "Una captura especial entre peones.",
  "lesson.enpassant.step.0": "Un peón contrario avanza dos casillas. Queda al lado de tu peón.",
  "lesson.enpassant.step.1": "Puedes capturarlo como si hubiera avanzado solo una casilla.",
  "lesson.enpassant.step.2": "Tu peón va en diagonal a la casilla que el otro peón saltó.",
  "lesson.enpassant.step.3": "Solo puedes hacerlo en tu siguiente jugada. Después se pierde la oportunidad.",
  "lesson.enpassant.q.0": "¿Cuándo puedes hacer una captura al paso?",
  "lesson.enpassant.q.0.hint": "La oportunidad dura una sola jugada.",
  "lesson.enpassant.q.0.a.0": "Justo después del avance de dos casillas",
  "lesson.enpassant.q.0.a.1": "En cualquier turno posterior",
  "lesson.enpassant.q.0.a.2": "Cuando un caballo salta",
  "lesson.enpassant.q.1": "¿Qué piezas hacen la captura al paso?",
  "lesson.enpassant.q.1.hint": "Es una jugada especial entre dos peones.",
  "lesson.enpassant.q.1.a.0": "Los peones",
  "lesson.enpassant.q.1.a.1": "Las torres",
  "lesson.enpassant.q.1.a.2": "Los reyes",
  "lesson.draw.title": "Una partida también puede empatar",
  "lesson.draw.intro": "A veces no gana ningún lado.",
  "lesson.draw.step.0": "Un empate se llama tablas. No gana ningún lado.",
  "lesson.draw.step.1": "Si no hay jugadas legales y no hay jaque, es ahogado. Son tablas.",
  "lesson.draw.step.2": "También hay tablas si quedan solo los dos reyes.",
  "lesson.draw.step.3": "Al repetir una posición tres veces, puedes pedir tablas.",
  "lesson.draw.q.0": "No hay jaque. No puedes hacer ninguna jugada legal. ¿Qué ocurre?",
  "lesson.draw.q.0.hint": "En el ahogado, el rey no está atacado.",
  "lesson.draw.q.0.a.0": "Es ahogado. La partida queda en tablas",
  "lesson.draw.q.0.a.1": "Es jaque mate",
  "lesson.draw.q.0.a.2": "Puedes mover una pieza contraria",
  "lesson.draw.q.1": "Solo quedan los dos reyes. ¿Quién gana?",
  "lesson.draw.q.1.hint": "Un rey solo no puede dar jaque mate.",
  "lesson.draw.q.1.a.0": "Nadie. Son tablas",
  "lesson.draw.q.1.a.1": "Las blancas",
  "lesson.draw.q.1.a.2": "Las negras",
  "app.tagline": "Ajedrez, paso a paso.",
  "app.title": "Enroca — Ajedrez, paso a paso",
  "app.description": "Aprende ajedrez con lecciones cortas, ejercicios y partidas con ayuda.",
  "nav.home": "Inicio",
  "nav.learn": "Aprende",
  "nav.practice": "Practica",
  "nav.play": "Juega",
  "nav.settings": "Ajustes",
  "nav.skip": "Ir al contenido",
  "nav.suite": "Más apps de Apptonomia",
  "home.eyebrow": "UN PEQUEÑO PASO. UNA NUEVA JUGADA.",
  "home.title": "El ajedrez empieza contigo.",
  "home.intro": "Conoce las piezas. Prueba lo que has aprendido. Disfruta jugando.",
  "home.cta": "Vamos a aprender",
  "home.resume": "Sigue por donde ibas",
  "home.note": "Sin reloj. Con ayuda. A tu ritmo.",
  "home.path": "Tu camino en el ajedrez",
  "home.pathIntro": "Puedes empezar por el primer paso o elegir otro.",
  "home.learn": "Conoce el tablero y las piezas con ejemplos.",
  "home.practice": "Prueba lo que recuerdas. Puedes pedir una pista.",
  "home.play": "Haz tu próxima jugada con ayuda a tu lado.",
  "home.learnCount": "14 lecciones cortas",
  "home.practiceCount": "28 ejercicios para probar",
  "home.playCount": "A solas o en compañía",
  "home.progress": "Has visto {n} de {total} lecciones.",
  "home.start": "Cada pieza tiene su camino. Vamos a descubrirlo.",
  "common.back": "Volver",
  "common.next": "Siguiente",
  "common.previous": "Anterior",
  "common.done": "Visto",
  "common.pending": "Por descubrir",
  "common.cancel": "Cancelar",
  "common.close": "Cerrar",
  "common.continue": "Continuar",
  "common.listen": "Escuchar",
  "common.stop": "Dejar de escuchar",
  "common.voiceUnavailable": "No hay una voz local disponible. Puedes seguir leyendo.",
  "common.offline": "Estás sin conexión. Puedes seguir jugando.",
  "common.storageUnavailable": "Puedes seguir. Este navegador no permite guardar tus avances.",
  "common.saved": "Tus avances se guardan en este dispositivo.",
  "learn.title": "Aprende una cosa cada vez.",
  "learn.intro": "Mira el ejemplo. Lee o escucha. Repite cuando quieras.",
  "learn.step": "Paso {n} de {total}",
  "learn.example": "Mira un ejemplo",
  "learn.reset": "Ver la posición inicial",
  "learn.diagram": "Ejemplo del tablero",
  "learn.legend": "Los puntos muestran destinos. Las piezas se mueven siguiendo su regla.",
  "learn.finish": "He visto esta lección",
  "learn.finished": "Lección vista. Ahora puedes probar lo aprendido.",
  "learn.practice": "Practicar esta lección",
  "learn.other": "Ver las lecciones",
  "learn.readAgain": "Volver a leer",
  "learn.reading": "Ver lección",
  "practice.title": "Vamos a probar lo aprendido.",
  "practice.intro": "Un ejercicio cada vez. Las pistas están para ayudarte.",
  "practice.all": "Practicar desde el principio",
  "practice.review": "Elige una lección para practicar",
  "practice.summary": "Has resuelto {n} de {total} ejercicios.",
  "practice.number": "Ejercicio {n} de {total}",
  "practice.hint": "Dame una pista",
  "practice.lesson": "Volver a la lección",
  "practice.return": "Volver al ejercicio",
  "practice.again": "Vamos a mirarlo otra vez. Puedes probar otra opción.",
  "practice.right": "¡Lo has encontrado!",
  "practice.supported": "Resuelto con ayuda. Puedes repetirlo cuando quieras.",
  "practice.independent": "Resuelto sin pista",
  "practice.withHint": "Resuelto con ayuda",
  "practice.choosePiece": "Primero toca la pieza que vas a mover.",
  "practice.chooseSquare": "Ahora toca la casilla de destino.",
  "practice.invalid": "Esa casilla no es el destino que buscamos. Mira la pregunta.",
  "practice.complete": "Has terminado esta práctica.",
  "practice.completeText": "Puedes repetir, ver otra lección o jugar una partida.",
  "practice.repeat": "Repetir esta práctica",
  "practice.toGame": "Vamos a jugar",
  "play.title": "Cada jugada es un nuevo paso.",
  "play.intro": "Elige cómo quieres jugar. Tendrás ayuda durante la partida.",
  "play.boardType": "¿Con cuántas piezas?",
  "play.mini": "Primeros pasos",
  "play.miniDesc": "Pocas piezas. Tú tienes una torre para ayudarte.",
  "play.full": "Todas las piezas",
  "play.fullDesc": "El tablero completo. Las mismas ayudas.",
  "play.partner": "¿Con quién juegas?",
  "play.computer": "Con Enroca",
  "play.computerDesc": "Tú llevas las blancas. Enroca lleva las negras.",
  "play.local": "Con otra persona",
  "play.localDesc": "Compartís este dispositivo y jugáis por turnos.",
  "play.start": "Empezar la partida",
  "play.resume": "Continuar mi partida",
  "play.new": "Nueva partida",
  "play.newTitle": "¿Empezar otra partida?",
  "play.newText": "La partida actual se cambiará por una nueva. Tus lecciones se guardan.",
  "play.whiteTurn": "Turno de las blancas",
  "play.blackTurn": "Turno de las negras",
  "play.thinking": "Enroca está eligiendo su jugada.",
  "play.select": "1. Toca una de tus piezas.",
  "play.destination": "2. Toca un destino con un punto o un aro.",
  "play.selected": "{piece} en {square}. Elige su destino.",
  "play.noMoves": "Esa pieza no puede moverse ahora. Prueba con otra.",
  "play.invalid": "Ese movimiento no está permitido. Prueba un destino marcado.",
  "play.check": "Jaque. Tu próxima jugada debe proteger al rey.",
  "play.hint": "Ayúdame a elegir",
  "play.undo": "Deshacer jugada",
  "play.hintText": "Puedes mover {piece} de {from} a {to}.",
  "play.legend": "● Puedes ir aquí · ◎ Puedes capturar aquí",
  "play.board": "Tablero de ajedrez. Usa las flechas para recorrer las casillas.",
  "play.keyboard": "Teclado: flechas para elegir casilla. Intro para tocar. Escape para soltar.",
  "play.empty": "{square}, vacía",
  "play.square": "{square}, {side}: {piece}",
  "play.destinationLabel": "destino posible",
  "play.captureLabel": "captura posible",
  "play.selectedLabel": "seleccionada",
  "play.white": "Blancas",
  "play.black": "Negras",
  "play.you": "Tú",
  "play.moved": "{side}: {piece}, de {from} a {to}.",
  "play.captured": "Captura {piece}.",
  "play.castled": "El rey y la torre han enrocado.",
  "play.promoted": "El peón se ha convertido en {piece}.",
  "play.enpassant": "Captura al paso: sale el peón de la casilla vecina.",
  "play.lastMove": "Última jugada",
  "play.noLastMove": "Las blancas empiezan.",
  "play.promotion": "Tu peón ha llegado. Elige su nueva pieza.",
  "play.mate": "Jaque mate. Ganan las {side}.",
  "play.stalemate": "Tablas por ahogado. No hay jaque ni jugadas posibles.",
  "play.material": "Tablas. Estas piezas no pueden dar jaque mate.",
  "play.fivefold": "Tablas. La misma posición se ha repetido cinco veces.",
  "play.seventyfive": "Tablas. Han pasado 75 turnos por lado sin mover peones ni capturar.",
  "play.fifty": "Tablas solicitadas tras 50 turnos por lado sin mover peones ni capturar.",
  "play.threefold": "Tablas solicitadas al repetir la misma posición tres veces.",
  "play.claim": "Pedir tablas",
  "play.claimAvailable": "Puedes pedir tablas por repetición o por muchos turnos sin avances.",
  "play.endNote": "Puedes mirar el tablero con calma o empezar otra partida.",
  "play.history": "Ver las jugadas de esta partida",
  "piece.p": "peón",
  "piece.r": "torre",
  "piece.n": "caballo",
  "piece.b": "alfil",
  "piece.q": "dama",
  "piece.k": "rey",
  "settings.title": "Hazlo a tu manera.",
  "settings.intro": "Elige las ayudas que te resulten cómodas.",
  "settings.language": "Idioma",
  "settings.text": "Tamaño del texto",
  "settings.regular": "Normal",
  "settings.large": "Grande",
  "settings.contrast": "Contraste alto",
  "settings.pieceNames": "Mostrar nombres bajo las piezas",
  "settings.data": "Lo que guarda Enroca",
  "settings.dataText": "Aquí se guardan tus lecciones vistas, ejercicios resueltos, ajustes y partida actual.",
  "settings.privacy": "Todo queda en este navegador. No necesitas una cuenta.",
  "settings.delete": "Borrar mis datos",
  "settings.confirmTitle": "¿Borrar tus datos de Enroca?",
  "settings.confirmText": "Se borrarán tus avances, ajustes y partida en este dispositivo.",
  "settings.confirm": "Sí, borrar mis datos",
  "settings.deleted": "Tus datos de Enroca se han borrado.",
  "footer.note": "Una app de Apptonomia. Aprende a tu ritmo.",
  "privacy.title": "Tus datos se quedan contigo.",
  "privacy.intro": "Enroca no pide tu nombre ni tu correo.",
  "privacy.storage": "Guarda tus avances y tu partida solo en este navegador.",
  "privacy.tracking": "No usa cookies, anuncios, cuentas ni seguimiento.",
  "privacy.voice": "Escuchar usa una voz del dispositivo. Si no hay una, puedes leer.",
  "privacy.reset": "Puedes borrar los datos desde Ajustes.",
  "privacy.link": "Privacidad",
  "support.link": "Guía de acompañamiento",
  "play.list": "Mover con una lista",
  "play.from": "Elige una pieza",
  "play.to": "Elige su destino",
  "play.move": "Mover la pieza",
  "play.choose": "Elige una opción",
  "play.listHelp": "También puedes elegir las casillas con estos botones grandes."
});
