/* Enroca — es; Spanish is the editorial source of truth. */
window.App.i18n.register('es', {
  suiteBy: 'Una app de',
  "lesson.board.title": "Conoce el tablero",
  "lesson.board.intro": "El tablero es el lugar donde juegas.",
  "lesson.board.step.0": "Este es el tablero. Tiene casillas claras y oscuras.",
  "lesson.board.step.1": "Cada casilla tiene una letra y un número. Esta es a1.",
  "lesson.turns.title": "Una jugada cada vez",
  "lesson.turns.intro": "Cada persona tiene su turno.",
  "lesson.turns.step.0": "Una persona lleva las piezas blancas. La otra lleva las negras.",
  "lesson.turns.step.1": "Las blancas empiezan. Después juegan las negras.",
  "lesson.turns.step.2": "Mueve una pieza en tu turno. Después espera el otro turno.",
  "lesson.turns.q.0": "¿Qué piezas empiezan la partida?",
  "lesson.turns.q.0.hint": "Primero juegan las blancas. Después juegan las negras.",
  "lesson.turns.q.0.a.0": "Las blancas",
  "lesson.turns.q.0.a.1": "Las negras",
  "lesson.turns.q.0.a.2": "Las dos a la vez",
  "lesson.turns.q.1": "Acabas de mover tus piezas blancas. ¿Qué haces ahora?",
  "lesson.turns.q.1.hint": "Cada lado tiene su turno. No mueves dos veces seguidas.",
  "lesson.turns.q.1.a.0": "Esperar a las negras",
  "lesson.turns.q.1.a.1": "Mover otra pieza blanca",
  "lesson.turns.q.1.a.2": "Mover una pieza negra también",
  "lesson.rook.title": "La torre va recta",
  "lesson.rook.intro": "Arriba, abajo o hacia los lados.",
  "lesson.rook.step.0": "La torre se mueve en línea recta.",
  "lesson.rook.step.1": "Puede ir arriba, abajo, a la izquierda o a la derecha.",
  "lesson.rook.step.2": "Puede avanzar varias casillas. No puede saltar otras piezas.",
  "lesson.rook.q.0": "¿Cómo se mueve la torre?",
  "lesson.rook.q.0.hint": "La torre va por una fila o por una columna.",
  "lesson.rook.q.0.a.0": "En línea recta",
  "lesson.rook.q.0.a.1": "En diagonal",
  "lesson.rook.q.0.a.2": "Saltando en forma de L",
  "lesson.rook.target": "Mueve la pieza a d7.",
  "lesson.rook.target.hint": "Toca la pieza. Después toca d7. Mira el camino.",
  "lesson.bishop.title": "El alfil va en diagonal",
  "lesson.bishop.intro": "Sigue un camino inclinado.",
  "lesson.bishop.step.0": "El alfil se mueve en diagonal. Es un camino inclinado.",
  "lesson.bishop.step.1": "El alfil siempre sigue casillas del mismo color.",
  "lesson.bishop.step.2": "Puede avanzar varias casillas. No puede saltar otras piezas.",
  "lesson.bishop.q.0": "¿Cómo se mueve el alfil?",
  "lesson.bishop.q.0.hint": "Busca el camino inclinado. Sus casillas tienen el mismo color.",
  "lesson.bishop.q.0.a.0": "En diagonal",
  "lesson.bishop.q.0.a.1": "Solo hacia delante",
  "lesson.bishop.q.0.a.2": "En línea recta",
  "lesson.bishop.target": "Mueve la pieza a f6.",
  "lesson.bishop.target.hint": "Toca la pieza. Después toca f6. Mira el camino.",
  "lesson.queen.title": "La dama tiene dos caminos",
  "lesson.queen.intro": "En línea recta y en diagonal.",
  "lesson.queen.step.0": "La dama puede moverse en línea recta, como la torre.",
  "lesson.queen.step.1": "También puede moverse en diagonal, como el alfil.",
  "lesson.queen.step.2": "Puede avanzar varias casillas. No puede saltar otras piezas.",
  "lesson.queen.q.0": "¿Qué caminos puede seguir la dama?",
  "lesson.queen.q.0.hint": "La dama combina los caminos de la torre y del alfil.",
  "lesson.queen.q.0.a.0": "Rectos y diagonales",
  "lesson.queen.q.0.a.1": "Solo diagonales",
  "lesson.queen.q.0.a.2": "Solo una casilla hacia delante",
  "lesson.queen.target": "Mueve la pieza a g7.",
  "lesson.queen.target.hint": "Toca la pieza. Después toca g7. Mira el camino.",
  "lesson.king.title": "Cuida a tu rey",
  "lesson.king.intro": "Un paso, con cuidado.",
  "lesson.king.step.0": "El rey se mueve una casilla en cualquier dirección.",
  "lesson.king.step.1": "El rey no puede ir a una casilla atacada.",
  "lesson.king.step.2": "Los dos reyes nunca pueden estar en casillas vecinas.",
  "lesson.king.q.0": "En un movimiento normal, ¿cuánto avanza el rey?",
  "lesson.king.q.0.hint": "El rey da un paso. Después espera su próximo turno.",
  "lesson.king.q.0.a.0": "Una casilla",
  "lesson.king.q.0.a.1": "Toda una fila",
  "lesson.king.q.0.a.2": "Tres casillas",
  "lesson.king.target": "Mueve la pieza a e5.",
  "lesson.king.target.hint": "Toca la pieza. Después toca e5. Mira el camino.",
  "lesson.knight.title": "El caballo salta",
  "lesson.knight.intro": "Dos casillas y una al lado.",
  "lesson.knight.step.0": "El caballo se mueve en forma de L.",
  "lesson.knight.step.1": "Cuenta dos casillas en línea recta. Después, una hacia un lado.",
  "lesson.knight.step.2": "El caballo puede saltar otras piezas. Es la única pieza que salta.",
  "lesson.knight.q.0": "¿Qué pieza puede saltar otras piezas?",
  "lesson.knight.q.0.hint": "Recuerda el salto en forma de L.",
  "lesson.knight.q.0.a.0": "El caballo",
  "lesson.knight.q.0.a.1": "La torre",
  "lesson.knight.q.0.a.2": "El alfil",
  "lesson.knight.target": "Mueve la pieza a e6.",
  "lesson.knight.target.hint": "Toca la pieza. Después toca e6. Mira el camino.",
  "lesson.pawn.title": "El peón va hacia delante",
  "lesson.pawn.intro": "Avanza recto. Captura en diagonal.",
  "lesson.pawn.step.0": "El peón avanza una casilla hacia delante. No retrocede.",
  "lesson.pawn.step.1": "Desde su casilla inicial, puede avanzar dos casillas si están libres.",
  "lesson.pawn.step.2": "El peón captura una pieza contraria en la casilla diagonal de delante.",
  "lesson.pawn.q.0": "¿Cómo captura el peón?",
  "lesson.pawn.q.0.hint": "Para avanzar va recto. Para capturar va en diagonal.",
  "lesson.pawn.q.0.a.0": "Una casilla en diagonal hacia delante",
  "lesson.pawn.q.0.a.1": "Una casilla hacia atrás",
  "lesson.pawn.q.0.a.2": "Dos casillas hacia un lado",
  "lesson.pawn.target": "Mueve la pieza a d3.",
  "lesson.pawn.target.hint": "Toca la pieza. Después toca d3. Mira el camino.",
  "lesson.capture.title": "Capturar una pieza",
  "lesson.capture.intro": "Ocupa la casilla de una pieza contraria.",
  "lesson.capture.step.0": "Capturar es llegar a la casilla de una pieza contraria.",
  "lesson.capture.step.1": "La pieza contraria sale del tablero. Tu pieza ocupa su lugar.",
  "lesson.capture.step.2": "No puedes capturar tus propias piezas. El rey nunca se captura.",
  "lesson.capture.q.0": "Tu torre encuentra una pieza de tu color. ¿Puede capturarla?",
  "lesson.capture.q.0.hint": "Solo puedes capturar piezas del otro color. El rey nunca se captura.",
  "lesson.capture.q.0.a.0": "No. Es una pieza de mi lado",
  "lesson.capture.q.0.a.1": "Sí. Puede capturarla",
  "lesson.capture.q.0.a.2": "Sí. Si es un peón",
  "lesson.capture.target": "Mueve la pieza a d7.",
  "lesson.capture.target.hint": "Toca la pieza. Después toca d7. Mira el camino.",
  "lesson.check.title": "Jaque: protege al rey",
  "lesson.check.intro": "El rey está atacado.",
  "lesson.check.step.0": "Hay jaque cuando una pieza contraria ataca a tu rey.",
  "lesson.check.step.1": "Debes quitar el jaque: mover el rey, tapar el ataque o capturar.",
  "lesson.check.step.2": "Si no hay ninguna salida, es jaque mate. La partida termina.",
  "lesson.check.q.0": "Tu rey está en jaque. ¿Qué debes hacer?",
  "lesson.check.q.0.hint": "Tu próxima jugada debe dejar a tu rey a salvo.",
  "lesson.check.q.0.a.0": "Quitar el ataque al rey",
  "lesson.check.q.0.a.1": "Mover cualquier peón",
  "lesson.check.q.0.a.2": "Esperar un turno",
  "lesson.check.q.1": "Hay jaque y no existe ninguna salida. ¿Qué ocurre?",
  "lesson.check.q.1.hint": "La partida termina antes de capturar al rey.",
  "lesson.check.q.1.a.0": "Es jaque mate. La partida termina",
  "lesson.check.q.1.a.1": "El rey salta sobre otra pieza",
  "lesson.check.q.1.a.2": "El otro lado captura al rey",
  "lesson.castle.title": "El enroque",
  "lesson.castle.intro": "El rey y la torre se mueven juntos.",
  "lesson.castle.step.0": "El enroque es una jugada especial del rey y una torre.",
  "lesson.castle.step.1": "El rey avanza dos casillas hacia la torre. La torre queda junto al rey.",
  "lesson.castle.step.2": "Ninguna de esas piezas puede haberse movido. El camino debe estar libre.",
  "lesson.castle.step.3": "El rey no puede estar en jaque, pasar por un ataque ni acabar atacado.",
  "lesson.castle.q.0": "¿Qué piezas participan en el enroque?",
  "lesson.castle.q.0.hint": "Enrocar ayuda al rey a cambiar de lugar junto a una torre.",
  "lesson.castle.q.0.a.0": "El rey y una torre",
  "lesson.castle.q.0.a.1": "La dama y un caballo",
  "lesson.castle.q.0.a.2": "Dos peones",
  "lesson.castle.q.1": "Tu rey está en jaque. ¿Puedes enrocar ahora?",
  "lesson.castle.q.1.hint": "El enroque no puede empezar con el rey en jaque.",
  "lesson.castle.q.1.a.0": "No. Primero hay que quitar el jaque",
  "lesson.castle.q.1.a.1": "Sí. Siempre",
  "lesson.castle.q.1.a.2": "Sí. Si la torre no se ha movido",
  "lesson.promotion.title": "Un peón se transforma",
  "lesson.promotion.intro": "Llega al otro extremo del tablero.",
  "lesson.promotion.step.0": "Cuando un peón llega a la última fila, cambia de pieza.",
  "lesson.promotion.step.1": "Puedes elegir dama, torre, alfil o caballo. Esto se llama coronación.",
  "lesson.promotion.step.2": "No puedes elegir un rey ni dejarlo como peón.",
  "lesson.promotion.q.0": "Tu peón llega a la última fila. ¿En qué puede convertirse?",
  "lesson.promotion.q.0.hint": "Puedes elegir dama, torre, alfil o caballo.",
  "lesson.promotion.q.0.a.0": "En una dama",
  "lesson.promotion.q.0.a.1": "En otro rey",
  "lesson.promotion.q.0.a.2": "Debe seguir siendo peón",
  "lesson.promotion.q.1": "¿Cómo se llama el cambio del peón por otra pieza?",
  "lesson.promotion.q.1.hint": "Al llegar a la última fila, el peón se transforma.",
  "lesson.promotion.q.1.a.0": "Coronación",
  "lesson.promotion.q.1.a.1": "Enroque",
  "lesson.promotion.q.1.a.2": "Jaque",
  "lesson.enpassant.title": "La captura al paso",
  "lesson.enpassant.intro": "Una captura especial entre peones.",
  "lesson.enpassant.step.0": "Un peón contrario avanza dos casillas. Queda al lado de tu peón.",
  "lesson.enpassant.step.1": "Puedes capturarlo como si hubiera avanzado solo una casilla.",
  "lesson.enpassant.step.2": "Tu peón va en diagonal a la casilla que el otro peón saltó.",
  "lesson.enpassant.step.3": "Solo puedes hacerlo en tu siguiente jugada. Después se pierde la oportunidad.",
  "lesson.enpassant.q.0": "¿Cuándo puedes hacer una captura al paso?",
  "lesson.enpassant.q.0.hint": "La oportunidad dura una sola jugada.",
  "lesson.enpassant.q.0.a.0": "Justo después del avance de dos casillas",
  "lesson.enpassant.q.0.a.1": "En cualquier turno posterior",
  "lesson.enpassant.q.0.a.2": "Cuando un caballo salta",
  "lesson.enpassant.q.1": "¿Qué piezas hacen la captura al paso?",
  "lesson.enpassant.q.1.hint": "Es una jugada especial entre dos peones.",
  "lesson.enpassant.q.1.a.0": "Los peones",
  "lesson.enpassant.q.1.a.1": "Las torres",
  "lesson.enpassant.q.1.a.2": "Los reyes",
  "lesson.draw.title": "Una partida también puede empatar",
  "lesson.draw.intro": "A veces no gana ningún lado.",
  "lesson.draw.step.0": "Un empate se llama tablas. No gana ningún lado.",
  "lesson.draw.step.1": "Si no hay jugadas legales y no hay jaque, es ahogado. Son tablas.",
  "lesson.draw.step.2": "También hay tablas si quedan solo los dos reyes.",
  "lesson.draw.step.3": "Al repetir una posición tres veces, puedes pedir tablas.",
  "lesson.draw.q.0": "No hay jaque. No puedes hacer ninguna jugada legal. ¿Qué ocurre?",
  "lesson.draw.q.0.hint": "En el ahogado, el rey no está atacado.",
  "lesson.draw.q.0.a.0": "Es ahogado. La partida queda en tablas",
  "lesson.draw.q.0.a.1": "Es jaque mate",
  "lesson.draw.q.0.a.2": "Puedes mover una pieza contraria",
  "lesson.draw.q.1": "Solo quedan los dos reyes. ¿Quién gana?",
  "lesson.draw.q.1.hint": "Un rey solo no puede dar jaque mate.",
  "lesson.draw.q.1.a.0": "Nadie. Son tablas",
  "lesson.draw.q.1.a.1": "Las blancas",
  "lesson.draw.q.1.a.2": "Las negras",
  "app.tagline": "Ajedrez, paso a paso.",
  "app.title": "Enroca — Ajedrez, paso a paso",
  "app.description": "Ajedrez con tableros, piezas, retos y partidas.",
  "nav.home": "Inicio",
  "nav.learn": "Inicio",
  "nav.practice": "Retos",
  "nav.play": "Partida",
  "nav.settings": "Ajustes",
  "nav.skip": "Ir al contenido",
  "nav.suite": "Más apps de Apptonomia",
  "common.back": "Volver",
  "common.next": "Siguiente",
  "common.previous": "Anterior",
  "common.done": "Visto",
  "common.pending": "Por descubrir",
  "common.cancel": "Cancelar",
  "common.close": "Cerrar",
  "common.continue": "Continuar",
  "common.offline": "Estás sin conexión. Puedes seguir jugando.",
  "common.storageUnavailable": "Puedes seguir. Este navegador no permite guardar tus avances.",
  "common.saved": "Tus avances se guardan en este dispositivo.",
  "learn.title": "Aprende una cosa cada vez.",
  "learn.example": "Ver movimiento",
  "learn.reset": "Volver",
  "learn.diagram": "Ejemplo del tablero",
  "learn.other": "Inicio",
  "practice.title": "Vamos a probar lo aprendido.",
  "practice.hint": "Pista",
  "practice.lesson": "Ver de nuevo",
  "practice.return": "Volver",
  "practice.again": "Prueba otra casilla u opción.",
  "practice.right": "¡Bien!",
  "practice.choosePiece": "Toca la pieza.",
  "practice.chooseSquare": "Elige una casilla.",
  "practice.complete": "¡Listo!",
  "practice.repeat": "Repetir",
  "practice.toGame": "Una partida",
  "play.title": "Una partida",
  "play.boardType": "Piezas",
  "play.mini": "Pocas piezas",
  "play.miniDesc": "Reyes, peones y una torre.",
  "play.full": "Todas las piezas",
  "play.fullDesc": "La posición inicial.",
  "play.partner": "Rival",
  "play.computer": "Enroca",
  "play.computerDesc": "Tú llevas las blancas.",
  "play.local": "Otra persona",
  "play.localDesc": "En este dispositivo.",
  "play.start": "Empezar",
  "play.resume": "Continuar mi partida",
  "play.new": "Nueva partida",
  "play.newTitle": "¿Empezar otra partida?",
  "play.newText": "Se sustituirá la partida actual.",
  "play.whiteTurn": "Turno de las blancas",
  "play.blackTurn": "Turno de las negras",
  "play.thinking": "Turno de Enroca",
  "play.select": "Toca una pieza de las {side}.",
  "play.destination": "Elige una casilla marcada.",
  "play.selected": "{piece} en {square}.",
  "play.noMoves": "Elige otra pieza.",
  "play.invalid": "Elige una casilla marcada.",
  "play.check": "Jaque. Tu próxima jugada debe proteger al rey.",
  "play.hint": "Pista",
  "play.undo": "Deshacer",
  "play.hintText": "{piece}: {from} → {to}.",
  "play.legend": "● Destino · ◎ Captura",
  "play.board": "Tablero de ajedrez. Usa las flechas para recorrer las casillas.",
  "play.keyboard": "Teclado: flechas para elegir casilla. Intro para tocar. Escape para soltar.",
  "play.empty": "{square}, vacía",
  "play.square": "{square}, {side}: {piece}",
  "play.destinationLabel": "destino posible",
  "play.captureLabel": "captura posible",
  "play.selectedLabel": "seleccionada",
  "play.white": "Blancas",
  "play.black": "Negras",
  "play.you": "Tú",
  "play.moved": "{side}: {piece}, de {from} a {to}.",
  "play.captured": "Captura {piece}.",
  "play.castled": "El rey y la torre han enrocado.",
  "play.promoted": "El peón se ha convertido en {piece}.",
  "play.enpassant": "Captura al paso: sale el peón de la casilla vecina.",
  "play.lastMove": "Última jugada",
  "play.noLastMove": "Las blancas empiezan.",
  "play.promotion": "Tu peón ha llegado. Elige su nueva pieza.",
  "play.mate": "Jaque mate. Ganan las {side}.",
  "play.stalemate": "Tablas por ahogado. No hay jaque ni jugadas posibles.",
  "play.material": "Tablas. Estas piezas no pueden dar jaque mate.",
  "play.fivefold": "Tablas. La misma posición se ha repetido cinco veces.",
  "play.seventyfive": "Tablas. Han pasado 75 turnos por lado sin mover peones ni capturar.",
  "play.fifty": "Tablas solicitadas tras 50 turnos por lado sin mover peones ni capturar.",
  "play.threefold": "Tablas solicitadas al repetir la misma posición tres veces.",
  "play.claim": "Pedir tablas",
  "play.claimAvailable": "Puedes pedir tablas por repetición o por muchos turnos sin avances.",
  "play.history": "Ver las jugadas de esta partida",
  "piece.p": "peón",
  "piece.r": "torre",
  "piece.n": "caballo",
  "piece.b": "alfil",
  "piece.q": "dama",
  "piece.k": "rey",
  "settings.title": "Ajustes",
  "settings.language": "Idioma",
  "settings.text": "Tamaño del texto",
  "settings.regular": "Normal",
  "settings.large": "Grande",
  "settings.contrast": "Contraste alto",
  "settings.pieceNames": "Nombres de piezas",
  "settings.data": "Datos guardados",
  "settings.privacy": "Todo queda en este navegador. No necesitas una cuenta.",
  "settings.delete": "Borrar datos",
  "settings.confirmTitle": "¿Borrar tus datos de Enroca?",
  "settings.confirmText": "Se borrarán tus avances, ajustes y partida en este dispositivo.",
  "settings.confirm": "Sí, borrar mis datos",
  "settings.deleted": "Tus datos de Enroca se han borrado.",
  "footer.note": "Una app de Apptonomia.",
  "privacy.title": "Tus datos se quedan contigo.",
  "privacy.intro": "Enroca no pide tu nombre ni tu correo.",
  "privacy.storage": "Guarda tus avances y tu partida solo en este navegador.",
  "privacy.tracking": "No usa cookies, anuncios, cuentas ni seguimiento.",
  "privacy.reset": "Puedes borrar los datos desde Ajustes.",
  "privacy.link": "Privacidad",
  "support.link": "Guía de acompañamiento",
  "play.list": "Elegir por nombre",
  "play.from": "Elige una pieza",
  "play.to": "Elige su destino",
  "play.move": "Mover",
  "play.choose": "Elige una opción",
  "mini.title": "Retos",
  "mini.open": "Ver retos",
  "mini.summary": "{n} de {total} resueltos",
  "mini.group.arrive": "A la bandera",
  "mini.group.path": "Busca un camino",
  "mini.group.protect": "Protege al rey",
  "mini.completed": "Resuelto",
  "mini.boardSize": "{n} × {n}",
  "mini.back": "Retos",
  "mini.return": "Volver al reto",
  "mini.goal": "Llega a {square}.",
  "mini.captureGoal": "Captura en {square}.",
  "mini.safeGoal": "Protege al rey.",
  "mini.flag": "bandera: tu meta",
  "mini.kingLabel": "rey que debes proteger",
  "mini.attackerLabel": "pieza que ataca al rey",
  "mini.movable": "puedes mover esta pieza",
  "mini.flagLegend": "⚑ Meta",
  "mini.safeLegend": "♔ Tu rey · ! Ataque",
  "mini.board": "Tablero del minijuego. Las flechas recorren las casillas.",
  "mini.success": "¡Hecho!",
  "mini.select": "Toca tu {piece}.",
  "mini.destination": "Elige una casilla.",
  "mini.targetCount": "Bandera {n} de {total}.",
  "mini.next": "Siguiente",
  "mini.showMoves": "Ver movimientos",
  "mini.supportChoice": "Puedes quitar los puntos para probar sin ellos. La ayuda sigue disponible.",
  "mini.restart": "Repetir",
  "mini.rules": "Reglas del reto",
  "mini.rules.move": "Solo mueves tu pieza blanca. Las otras piezas están quietas.",
  "mini.rules.protect": "Tu rey debe quedar fuera del ataque. Después termina el reto.",
  "mini.reload": "Puedes volver desde la lección sin perder este tablero. Al recargar la página, el reto empieza de nuevo. Las metas resueltas quedan guardadas.",
  "mini.undone": "Volvemos aquí.",
  "mini.again": "Prueba otra casilla.",
  "mini.nextFlag": "¡Bien! Ve a la siguiente bandera.",
  "mini.moved": "{square}.",
  "mini.rook-flag.title": "La torre va recta",
  "mini.rook-flag.intro": "Lleva la torre a la bandera.",
  "mini.rook-flag.rule": "La torre va en línea recta: arriba, abajo o hacia los lados.",
  "mini.bishop-flag.title": "El camino del alfil",
  "mini.bishop-flag.intro": "Lleva el alfil a la bandera.",
  "mini.bishop-flag.rule": "El alfil va en diagonal: un camino inclinado. Sigue casillas del mismo color.",
  "mini.knight-flag.title": "Un salto de caballo",
  "mini.knight-flag.intro": "Lleva el caballo a la bandera. El peón se queda quieto.",
  "mini.knight-flag.rule": "El caballo avanza dos casillas y una hacia un lado. Puede saltar por encima del peón.",
  "mini.pawn-flag.title": "El peón avanza",
  "mini.pawn-flag.intro": "Lleva el peón a la bandera.",
  "mini.pawn-flag.rule": "El peón avanza hacia arriba. Puede dar un paso. Desde su casilla inicial puede dar dos si el camino está libre.",
  "mini.rook-path.title": "Dobla la esquina",
  "mini.rook-path.intro": "Lleva la torre a las dos banderas, una después de otra. El peón se queda quieto.",
  "mini.rook-path.rule": "La torre no salta el peón. Usa una línea recta en cada jugada. La siguiente bandera aparece al llegar.",
  "mini.bishop-path.title": "Rodea con el alfil",
  "mini.bishop-path.intro": "Lleva el alfil a la bandera. Busca un camino alrededor del peón.",
  "mini.bishop-path.rule": "El peón blanco se queda quieto. El alfil no puede saltarlo ni capturarlo. Prueba varias diagonales.",
  "mini.knight-path.title": "Salto a salto",
  "mini.knight-path.intro": "Lleva el caballo hasta la bandera. Puedes necesitar varios saltos.",
  "mini.knight-path.rule": "En cada salto, cuenta dos casillas y una hacia un lado. El peón se queda quieto.",
  "mini.pawn-capture.title": "Captura y avanza",
  "mini.pawn-capture.intro": "Mueve el peón de b2. Primero captura el peón negro. Después, llega a la nueva bandera.",
  "mini.pawn-capture.rule": "El peón captura una casilla en diagonal hacia arriba. Para avanzar sin capturar, va recto. El otro peón blanco se queda quieto.",
  "mini.king-step.title": "Aparta al rey",
  "mini.king-step.intro": "La torre negra ataca a tu rey. Mueve el rey a una casilla segura.",
  "mini.king-step.rule": "El rey da un paso. La casilla elegida no puede estar atacada. Puedes probar distintos destinos seguros.",
  "mini.rook-shield.title": "La torre hace de escudo",
  "mini.rook-shield.intro": "Mueve tu torre para tapar el ataque al rey.",
  "mini.rook-shield.rule": "Coloca la torre blanca entre la torre negra y tu rey. En este reto solo mueves la torre blanca.",
  "mini.bishop-capture.title": "Captura para proteger",
  "mini.bishop-capture.intro": "Mueve el alfil para capturar la torre que ataca a tu rey.",
  "mini.bishop-capture.rule": "El alfil captura en diagonal. En este reto solo mueves el alfil blanco.",
  "mini.choose-safety.title": "Elige cómo proteger",
  "mini.choose-safety.intro": "Tu rey está en jaque. Puedes mover el rey, la torre o el alfil blancos.",
  "mini.choose-safety.rule": "Busca una solución: apartar al rey o poner una pieza delante del ataque. Hay varias jugadas que sirven.",
  "topics.board": "El tablero",
  "topics.pieces": "Las piezas",
  "topics.match": "En la partida",
  "common.again": "Repetir",
  "settings.sounds": "Sonidos",
  "lesson.board.locate.a1": "Toca a1.",
  "lesson.board.locate.a1.hint": "Abajo, a la izquierda.",
  "lesson.board.locate.c3": "Toca c3.",
  "lesson.board.locate.c3.hint": "Busca la columna c y la fila 3.",
  "lesson.board.locate.h1": "Toca h1.",
  "lesson.board.locate.h1.hint": "Abajo, a la derecha.",
  "mini.selectAny": "Elige una pieza blanca.",
  "common.choose": "Elegir"
});
