name = "enroca"
compatibility_date = "2026-09-11"
routes = [{ pattern = "enroca.apptonomia.uk", custom_domain = true }]

[assets]
directory = "."
not_found_handling = "404-page"

[observability]
enabled = false
